/*
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class DslGrammarAccess extends AbstractGrammarElementFinder {
	
	public class RunTimeModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.RunTimeModel");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRunTimeModelAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cEnvDataAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cEnvDataEnvironmentMetaDataParserRuleCall_1_0 = (RuleCall)cEnvDataAssignment_1.eContents().get(0);
		private final Assignment cAppDataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAppDataAppMetaDataParserRuleCall_2_0 = (RuleCall)cAppDataAssignment_2.eContents().get(0);
		
		//RunTimeModel:
		//	{RunTimeModel} envData+=EnvironmentMetaData
		//	appData+=AppMetaData;
		@Override public ParserRule getRule() { return rule; }
		
		//{RunTimeModel} envData+=EnvironmentMetaData appData+=AppMetaData
		public Group getGroup() { return cGroup; }
		
		//{RunTimeModel}
		public Action getRunTimeModelAction_0() { return cRunTimeModelAction_0; }
		
		//envData+=EnvironmentMetaData
		public Assignment getEnvDataAssignment_1() { return cEnvDataAssignment_1; }
		
		//EnvironmentMetaData
		public RuleCall getEnvDataEnvironmentMetaDataParserRuleCall_1_0() { return cEnvDataEnvironmentMetaDataParserRuleCall_1_0; }
		
		//appData+=AppMetaData
		public Assignment getAppDataAssignment_2() { return cAppDataAssignment_2; }
		
		//AppMetaData
		public RuleCall getAppDataAppMetaDataParserRuleCall_2_0() { return cAppDataAppMetaDataParserRuleCall_2_0; }
	}
	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.State");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//State:
		//	name=ID;
		@Override public ParserRule getRule() { return rule; }
		
		//name=ID
		public Assignment getNameAssignment() { return cNameAssignment; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_0() { return cNameIDTerminalRuleCall_0; }
	}
	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cResourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCanKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cBeKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cStatesAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cStatesStateParserRuleCall_2_2_0 = (RuleCall)cStatesAssignment_2_2.eContents().get(0);
		private final Group cGroup_2_3 = (Group)cGroup_2.eContents().get(3);
		private final Keyword cCommaKeyword_2_3_0 = (Keyword)cGroup_2_3.eContents().get(0);
		private final Assignment cStatesAssignment_2_3_1 = (Assignment)cGroup_2_3.eContents().get(1);
		private final RuleCall cStatesStateParserRuleCall_2_3_1_0 = (RuleCall)cStatesAssignment_2_3_1.eContents().get(0);
		
		//Resource:
		//	"resource" name=ID ("can" "be" states+=State ("," states+=State)*)?;
		@Override public ParserRule getRule() { return rule; }
		
		//"resource" name=ID ("can" "be" states+=State ("," states+=State)*)?
		public Group getGroup() { return cGroup; }
		
		//"resource"
		public Keyword getResourceKeyword_0() { return cResourceKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//("can" "be" states+=State ("," states+=State)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//"can"
		public Keyword getCanKeyword_2_0() { return cCanKeyword_2_0; }
		
		//"be"
		public Keyword getBeKeyword_2_1() { return cBeKeyword_2_1; }
		
		//states+=State
		public Assignment getStatesAssignment_2_2() { return cStatesAssignment_2_2; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_2_2_0() { return cStatesStateParserRuleCall_2_2_0; }
		
		//("," states+=State)*
		public Group getGroup_2_3() { return cGroup_2_3; }
		
		//","
		public Keyword getCommaKeyword_2_3_0() { return cCommaKeyword_2_3_0; }
		
		//states+=State
		public Assignment getStatesAssignment_2_3_1() { return cStatesAssignment_2_3_1; }
		
		//State
		public RuleCall getStatesStateParserRuleCall_2_3_1_0() { return cStatesStateParserRuleCall_2_3_1_0; }
	}
	public class AppMetaDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.AppMetaData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAppKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cAppIDAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cAppIDIDTerminalRuleCall_1_0 = (RuleCall)cAppIDAssignment_1.eContents().get(0);
		private final RuleCall cLBRACEParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cSpecificationAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSpecificationSpecificationParserRuleCall_3_0 = (RuleCall)cSpecificationAssignment_3.eContents().get(0);
		private final RuleCall cRBRACEParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//AppMetaData:
		//	"app" appID=ID
		//	LBRACE
		//	specification=Specification
		//	RBRACE;
		@Override public ParserRule getRule() { return rule; }
		
		//"app" appID=ID LBRACE specification=Specification RBRACE
		public Group getGroup() { return cGroup; }
		
		//"app"
		public Keyword getAppKeyword_0() { return cAppKeyword_0; }
		
		//appID=ID
		public Assignment getAppIDAssignment_1() { return cAppIDAssignment_1; }
		
		//ID
		public RuleCall getAppIDIDTerminalRuleCall_1_0() { return cAppIDIDTerminalRuleCall_1_0; }
		
		//LBRACE
		public RuleCall getLBRACEParserRuleCall_2() { return cLBRACEParserRuleCall_2; }
		
		//specification=Specification
		public Assignment getSpecificationAssignment_3() { return cSpecificationAssignment_3; }
		
		//Specification
		public RuleCall getSpecificationSpecificationParserRuleCall_3_0() { return cSpecificationSpecificationParserRuleCall_3_0; }
		
		//RBRACE
		public RuleCall getRBRACEParserRuleCall_4() { return cRBRACEParserRuleCall_4; }
	}
	public class SpecificationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.Specification");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSpecIDAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSpecIDIDTerminalRuleCall_0_0 = (RuleCall)cSpecIDAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cPriorityKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cPriorityAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cPriorityINTTerminalRuleCall_1_1_0 = (RuleCall)cPriorityAssignment_1_1.eContents().get(0);
		private final Keyword cOnKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cTriggerAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTriggerTriggerParserRuleCall_3_0 = (RuleCall)cTriggerAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCommaKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cTriggerAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cTriggerTriggerParserRuleCall_4_1_0 = (RuleCall)cTriggerAssignment_4_1.eContents().get(0);
		private final Assignment cIfdoAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cIfdoIfDoSpecParserRuleCall_5_0 = (RuleCall)cIfdoAssignment_5.eContents().get(0);
		private final Assignment cElseIfDoAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cElseIfDoElseIfDoSpecParserRuleCall_6_0 = (RuleCall)cElseIfDoAssignment_6.eContents().get(0);
		private final Assignment cElseDoAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cElseDoElseDoSpecParserRuleCall_7_0 = (RuleCall)cElseDoAssignment_7.eContents().get(0);
		
		//Specification:
		//	specID=ID? ('priority' priority=INT)?
		//	'on' trigger+=Trigger ("," trigger+=Trigger)*
		//	ifdo=IfDoSpec
		//	elseIfDo+=ElseIfDoSpec*
		//	elseDo=ElseDoSpec?;
		@Override public ParserRule getRule() { return rule; }
		
		//specID=ID? ('priority' priority=INT)? 'on' trigger+=Trigger ("," trigger+=Trigger)* ifdo=IfDoSpec
		//elseIfDo+=ElseIfDoSpec* elseDo=ElseDoSpec?
		public Group getGroup() { return cGroup; }
		
		//specID=ID?
		public Assignment getSpecIDAssignment_0() { return cSpecIDAssignment_0; }
		
		//ID
		public RuleCall getSpecIDIDTerminalRuleCall_0_0() { return cSpecIDIDTerminalRuleCall_0_0; }
		
		//('priority' priority=INT)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'priority'
		public Keyword getPriorityKeyword_1_0() { return cPriorityKeyword_1_0; }
		
		//priority=INT
		public Assignment getPriorityAssignment_1_1() { return cPriorityAssignment_1_1; }
		
		//INT
		public RuleCall getPriorityINTTerminalRuleCall_1_1_0() { return cPriorityINTTerminalRuleCall_1_1_0; }
		
		//'on'
		public Keyword getOnKeyword_2() { return cOnKeyword_2; }
		
		//trigger+=Trigger
		public Assignment getTriggerAssignment_3() { return cTriggerAssignment_3; }
		
		//Trigger
		public RuleCall getTriggerTriggerParserRuleCall_3_0() { return cTriggerTriggerParserRuleCall_3_0; }
		
		//("," trigger+=Trigger)*
		public Group getGroup_4() { return cGroup_4; }
		
		//","
		public Keyword getCommaKeyword_4_0() { return cCommaKeyword_4_0; }
		
		//trigger+=Trigger
		public Assignment getTriggerAssignment_4_1() { return cTriggerAssignment_4_1; }
		
		//Trigger
		public RuleCall getTriggerTriggerParserRuleCall_4_1_0() { return cTriggerTriggerParserRuleCall_4_1_0; }
		
		//ifdo=IfDoSpec
		public Assignment getIfdoAssignment_5() { return cIfdoAssignment_5; }
		
		//IfDoSpec
		public RuleCall getIfdoIfDoSpecParserRuleCall_5_0() { return cIfdoIfDoSpecParserRuleCall_5_0; }
		
		//elseIfDo+=ElseIfDoSpec*
		public Assignment getElseIfDoAssignment_6() { return cElseIfDoAssignment_6; }
		
		//ElseIfDoSpec
		public RuleCall getElseIfDoElseIfDoSpecParserRuleCall_6_0() { return cElseIfDoElseIfDoSpecParserRuleCall_6_0; }
		
		//elseDo=ElseDoSpec?
		public Assignment getElseDoAssignment_7() { return cElseDoAssignment_7; }
		
		//ElseDoSpec
		public RuleCall getElseDoElseDoSpecParserRuleCall_7_0() { return cElseDoElseDoSpecParserRuleCall_7_0; }
	}
	public class TriggerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.Trigger");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cResourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cResourceResourceCrossReference_0_0 = (CrossReference)cResourceAssignment_0.eContents().get(0);
		private final RuleCall cResourceResourceIDTerminalRuleCall_0_0_1 = (RuleCall)cResourceResourceCrossReference_0_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cIsKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cAreKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cStateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStateStateParserRuleCall_2_0 = (RuleCall)cStateAssignment_2.eContents().get(0);
		
		//Trigger:
		//	resource=[Resource] ("is" | "are") state=State;
		@Override public ParserRule getRule() { return rule; }
		
		//resource=[Resource] ("is" | "are") state=State
		public Group getGroup() { return cGroup; }
		
		//resource=[Resource]
		public Assignment getResourceAssignment_0() { return cResourceAssignment_0; }
		
		//[Resource]
		public CrossReference getResourceResourceCrossReference_0_0() { return cResourceResourceCrossReference_0_0; }
		
		//ID
		public RuleCall getResourceResourceIDTerminalRuleCall_0_0_1() { return cResourceResourceIDTerminalRuleCall_0_0_1; }
		
		//"is" | "are"
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"is"
		public Keyword getIsKeyword_1_0() { return cIsKeyword_1_0; }
		
		//"are"
		public Keyword getAreKeyword_1_1() { return cAreKeyword_1_1; }
		
		//state=State
		public Assignment getStateAssignment_2() { return cStateAssignment_2; }
		
		//State
		public RuleCall getStateStateParserRuleCall_2_0() { return cStateStateParserRuleCall_2_0; }
	}
	public class IfDoSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.IfDoSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cConditionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cConditionOrElementParserRuleCall_1_0 = (RuleCall)cConditionAssignment_1.eContents().get(0);
		private final Keyword cDoKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cActionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cActionActionParserRuleCall_3_0 = (RuleCall)cActionAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cAndKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cActionAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cActionActionParserRuleCall_4_1_0 = (RuleCall)cActionAssignment_4_1.eContents().get(0);
		
		//IfDoSpec:
		//	'if' condition=OrElement 'do' action+=Action ("and" action+=Action)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'if' condition=OrElement 'do' action+=Action ("and" action+=Action)*
		public Group getGroup() { return cGroup; }
		
		//'if'
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }
		
		//condition=OrElement
		public Assignment getConditionAssignment_1() { return cConditionAssignment_1; }
		
		//OrElement
		public RuleCall getConditionOrElementParserRuleCall_1_0() { return cConditionOrElementParserRuleCall_1_0; }
		
		//'do'
		public Keyword getDoKeyword_2() { return cDoKeyword_2; }
		
		//action+=Action
		public Assignment getActionAssignment_3() { return cActionAssignment_3; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_3_0() { return cActionActionParserRuleCall_3_0; }
		
		//("and" action+=Action)*
		public Group getGroup_4() { return cGroup_4; }
		
		//"and"
		public Keyword getAndKeyword_4_0() { return cAndKeyword_4_0; }
		
		//action+=Action
		public Assignment getActionAssignment_4_1() { return cActionAssignment_4_1; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_4_1_0() { return cActionActionParserRuleCall_4_1_0; }
	}
	public class ElseIfDoSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.ElseIfDoSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cElseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cIfKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionOrElementParserRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final Keyword cDoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cActionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cActionActionParserRuleCall_4_0 = (RuleCall)cActionAssignment_4.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAndKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cActionAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cActionActionParserRuleCall_5_1_0 = (RuleCall)cActionAssignment_5_1.eContents().get(0);
		
		//ElseIfDoSpec:
		//	'else' 'if' condition=OrElement 'do' action+=Action ("and" action+=Action)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'else' 'if' condition=OrElement 'do' action+=Action ("and" action+=Action)*
		public Group getGroup() { return cGroup; }
		
		//'else'
		public Keyword getElseKeyword_0() { return cElseKeyword_0; }
		
		//'if'
		public Keyword getIfKeyword_1() { return cIfKeyword_1; }
		
		//condition=OrElement
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }
		
		//OrElement
		public RuleCall getConditionOrElementParserRuleCall_2_0() { return cConditionOrElementParserRuleCall_2_0; }
		
		//'do'
		public Keyword getDoKeyword_3() { return cDoKeyword_3; }
		
		//action+=Action
		public Assignment getActionAssignment_4() { return cActionAssignment_4; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_4_0() { return cActionActionParserRuleCall_4_0; }
		
		//("and" action+=Action)*
		public Group getGroup_5() { return cGroup_5; }
		
		//"and"
		public Keyword getAndKeyword_5_0() { return cAndKeyword_5_0; }
		
		//action+=Action
		public Assignment getActionAssignment_5_1() { return cActionAssignment_5_1; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_5_1_0() { return cActionActionParserRuleCall_5_1_0; }
	}
	public class ElseDoSpecElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.ElseDoSpec");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cElseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cActionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cActionActionParserRuleCall_2_0 = (RuleCall)cActionAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAndKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActionAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActionActionParserRuleCall_3_1_0 = (RuleCall)cActionAssignment_3_1.eContents().get(0);
		
		//ElseDoSpec:
		//	'else' 'do' action+=Action ("and" action+=Action)*;
		@Override public ParserRule getRule() { return rule; }
		
		//'else' 'do' action+=Action ("and" action+=Action)*
		public Group getGroup() { return cGroup; }
		
		//'else'
		public Keyword getElseKeyword_0() { return cElseKeyword_0; }
		
		//'do'
		public Keyword getDoKeyword_1() { return cDoKeyword_1; }
		
		//action+=Action
		public Assignment getActionAssignment_2() { return cActionAssignment_2; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_2_0() { return cActionActionParserRuleCall_2_0; }
		
		//("and" action+=Action)*
		public Group getGroup_3() { return cGroup_3; }
		
		//"and"
		public Keyword getAndKeyword_3_0() { return cAndKeyword_3_0; }
		
		//action+=Action
		public Assignment getActionAssignment_3_1() { return cActionAssignment_3_1; }
		
		//Action
		public RuleCall getActionActionParserRuleCall_3_1_0() { return cActionActionParserRuleCall_3_1_0; }
	}
	public class EnvironmentMetaDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.EnvironmentMetaData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEnvironmentMetaDataAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cEnvironmentKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cLBRACEParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cResourcesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cResourcesResourceParserRuleCall_3_0 = (RuleCall)cResourcesAssignment_3.eContents().get(0);
		private final RuleCall cRBRACEParserRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//EnvironmentMetaData:
		//	{EnvironmentMetaData}
		//	"environment"
		//	LBRACE
		//	resources+=Resource+
		//	// maybe some specification that apply globally....
		//	RBRACE;
		@Override public ParserRule getRule() { return rule; }
		
		//{EnvironmentMetaData} "environment" LBRACE resources+=Resource+ // maybe some specification that apply globally....
		//RBRACE
		public Group getGroup() { return cGroup; }
		
		//{EnvironmentMetaData}
		public Action getEnvironmentMetaDataAction_0() { return cEnvironmentMetaDataAction_0; }
		
		//"environment"
		public Keyword getEnvironmentKeyword_1() { return cEnvironmentKeyword_1; }
		
		//LBRACE
		public RuleCall getLBRACEParserRuleCall_2() { return cLBRACEParserRuleCall_2; }
		
		//resources+=Resource+
		public Assignment getResourcesAssignment_3() { return cResourcesAssignment_3; }
		
		//Resource
		public RuleCall getResourcesResourceParserRuleCall_3_0() { return cResourcesResourceParserRuleCall_3_0; }
		
		//// maybe some specification that apply globally....
		//RBRACE
		public RuleCall getRBRACEParserRuleCall_4() { return cRBRACEParserRuleCall_4; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.Action");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cResourceAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final CrossReference cResourceResourceCrossReference_0_0 = (CrossReference)cResourceAssignment_0.eContents().get(0);
		private final RuleCall cResourceResourceIDTerminalRuleCall_0_0_1 = (RuleCall)cResourceResourceCrossReference_0_0.eContents().get(1);
		private final Keyword cColonEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cStateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cStateStateParserRuleCall_2_0 = (RuleCall)cStateAssignment_2.eContents().get(0);
		
		//Action:
		//	resource=[Resource] ":=" state=State;
		@Override public ParserRule getRule() { return rule; }
		
		//resource=[Resource] ":=" state=State
		public Group getGroup() { return cGroup; }
		
		//resource=[Resource]
		public Assignment getResourceAssignment_0() { return cResourceAssignment_0; }
		
		//[Resource]
		public CrossReference getResourceResourceCrossReference_0_0() { return cResourceResourceCrossReference_0_0; }
		
		//ID
		public RuleCall getResourceResourceIDTerminalRuleCall_0_0_1() { return cResourceResourceIDTerminalRuleCall_0_0_1; }
		
		//":="
		public Keyword getColonEqualsSignKeyword_1() { return cColonEqualsSignKeyword_1; }
		
		//state=State
		public Assignment getStateAssignment_2() { return cStateAssignment_2; }
		
		//State
		public RuleCall getStateStateParserRuleCall_2_0() { return cStateStateParserRuleCall_2_0; }
	}
	public class OrElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.OrElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndElementParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cOrKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cOrElementLeftAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndElementParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//OrElement Element:
		//	AndElement ("or" {OrElement.left=current} right=AndElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//AndElement ("or" {OrElement.left=current} right=AndElement)*
		public Group getGroup() { return cGroup; }
		
		//AndElement
		public RuleCall getAndElementParserRuleCall_0() { return cAndElementParserRuleCall_0; }
		
		//("or" {OrElement.left=current} right=AndElement)*
		public Group getGroup_1() { return cGroup_1; }
		
		//"or"
		public Keyword getOrKeyword_1_0() { return cOrKeyword_1_0; }
		
		//{OrElement.left=current}
		public Action getOrElementLeftAction_1_1() { return cOrElementLeftAction_1_1; }
		
		//right=AndElement
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//AndElement
		public RuleCall getRightAndElementParserRuleCall_1_2_0() { return cRightAndElementParserRuleCall_1_2_0; }
	}
	public class AndElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.AndElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cDiffEqualElementParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cAndKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cAndElementLeftAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightDiffEqualElementParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//AndElement Element:
		//	DiffEqualElement ("and" {AndElement.left=current} right=DiffEqualElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//DiffEqualElement ("and" {AndElement.left=current} right=DiffEqualElement)*
		public Group getGroup() { return cGroup; }
		
		//DiffEqualElement
		public RuleCall getDiffEqualElementParserRuleCall_0() { return cDiffEqualElementParserRuleCall_0; }
		
		//("and" {AndElement.left=current} right=DiffEqualElement)*
		public Group getGroup_1() { return cGroup_1; }
		
		//"and"
		public Keyword getAndKeyword_1_0() { return cAndKeyword_1_0; }
		
		//{AndElement.left=current}
		public Action getAndElementLeftAction_1_1() { return cAndElementLeftAction_1_1; }
		
		//right=DiffEqualElement
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//DiffEqualElement
		public RuleCall getRightDiffEqualElementParserRuleCall_1_2_0() { return cRightDiffEqualElementParserRuleCall_1_2_0; }
	}
	public class DiffEqualElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.DiffEqualElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCompareElementParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cExclamationMarkEqualsSignKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Action cDiffElementLeftAction_1_0_1 = (Action)cGroup_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cRightCompareElementParserRuleCall_1_0_2_0 = (RuleCall)cRightAssignment_1_0_2.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cEqualsSignEqualsSignKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Action cEqualElementLeftAction_1_1_1 = (Action)cGroup_1_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cRightCompareElementParserRuleCall_1_1_2_0 = (RuleCall)cRightAssignment_1_1_2.eContents().get(0);
		
		//DiffEqualElement Element:
		//	CompareElement ("!=" {DiffElement.left=current} right=CompareElement | "==" {EqualElement.left=current}
		//	right=CompareElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//CompareElement ("!=" {DiffElement.left=current} right=CompareElement | "==" {EqualElement.left=current}
		//right=CompareElement)*
		public Group getGroup() { return cGroup; }
		
		//CompareElement
		public RuleCall getCompareElementParserRuleCall_0() { return cCompareElementParserRuleCall_0; }
		
		//("!=" {DiffElement.left=current} right=CompareElement | "==" {EqualElement.left=current} right=CompareElement)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"!=" {DiffElement.left=current} right=CompareElement
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//"!="
		public Keyword getExclamationMarkEqualsSignKeyword_1_0_0() { return cExclamationMarkEqualsSignKeyword_1_0_0; }
		
		//{DiffElement.left=current}
		public Action getDiffElementLeftAction_1_0_1() { return cDiffElementLeftAction_1_0_1; }
		
		//right=CompareElement
		public Assignment getRightAssignment_1_0_2() { return cRightAssignment_1_0_2; }
		
		//CompareElement
		public RuleCall getRightCompareElementParserRuleCall_1_0_2_0() { return cRightCompareElementParserRuleCall_1_0_2_0; }
		
		//"==" {EqualElement.left=current} right=CompareElement
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//"=="
		public Keyword getEqualsSignEqualsSignKeyword_1_1_0() { return cEqualsSignEqualsSignKeyword_1_1_0; }
		
		//{EqualElement.left=current}
		public Action getEqualElementLeftAction_1_1_1() { return cEqualElementLeftAction_1_1_1; }
		
		//right=CompareElement
		public Assignment getRightAssignment_1_1_2() { return cRightAssignment_1_1_2; }
		
		//CompareElement
		public RuleCall getRightCompareElementParserRuleCall_1_1_2_0() { return cRightCompareElementParserRuleCall_1_1_2_0; }
	}
	public class CompareElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.CompareElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPlusMinusElementParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cGreaterThanSignKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Action cLargerElementLeftAction_1_0_1 = (Action)cGroup_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cRightPlusMinusElementParserRuleCall_1_0_2_0 = (RuleCall)cRightAssignment_1_0_2.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cGreaterThanSignEqualsSignKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Action cLargerEqualElementLeftAction_1_1_1 = (Action)cGroup_1_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cRightPlusMinusElementParserRuleCall_1_1_2_0 = (RuleCall)cRightAssignment_1_1_2.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Keyword cLessThanSignKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Action cSmallerElementLeftAction_1_2_1 = (Action)cGroup_1_2.eContents().get(1);
		private final Assignment cRightAssignment_1_2_2 = (Assignment)cGroup_1_2.eContents().get(2);
		private final RuleCall cRightPlusMinusElementParserRuleCall_1_2_2_0 = (RuleCall)cRightAssignment_1_2_2.eContents().get(0);
		private final Group cGroup_1_3 = (Group)cAlternatives_1.eContents().get(3);
		private final Keyword cEqualsSignLessThanSignKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Action cSmallerEqualElementLeftAction_1_3_1 = (Action)cGroup_1_3.eContents().get(1);
		private final Assignment cRightAssignment_1_3_2 = (Assignment)cGroup_1_3.eContents().get(2);
		private final RuleCall cRightPlusMinusElementParserRuleCall_1_3_2_0 = (RuleCall)cRightAssignment_1_3_2.eContents().get(0);
		
		//CompareElement Element:
		//	PlusMinusElement (">" {LargerElement.left=current} right=PlusMinusElement | ">=" {LargerEqualElement.left=current}
		//	right=PlusMinusElement | "<" {SmallerElement.left=current} right=PlusMinusElement | "=<"
		//	{SmallerEqualElement.left=current} right=PlusMinusElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//PlusMinusElement (">" {LargerElement.left=current} right=PlusMinusElement | ">=" {LargerEqualElement.left=current}
		//right=PlusMinusElement | "<" {SmallerElement.left=current} right=PlusMinusElement | "=<"
		//{SmallerEqualElement.left=current} right=PlusMinusElement)*
		public Group getGroup() { return cGroup; }
		
		//PlusMinusElement
		public RuleCall getPlusMinusElementParserRuleCall_0() { return cPlusMinusElementParserRuleCall_0; }
		
		//(">" {LargerElement.left=current} right=PlusMinusElement | ">=" {LargerEqualElement.left=current} right=PlusMinusElement
		//| "<" {SmallerElement.left=current} right=PlusMinusElement | "=<" {SmallerEqualElement.left=current}
		//right=PlusMinusElement)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//">" {LargerElement.left=current} right=PlusMinusElement
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//">"
		public Keyword getGreaterThanSignKeyword_1_0_0() { return cGreaterThanSignKeyword_1_0_0; }
		
		//{LargerElement.left=current}
		public Action getLargerElementLeftAction_1_0_1() { return cLargerElementLeftAction_1_0_1; }
		
		//right=PlusMinusElement
		public Assignment getRightAssignment_1_0_2() { return cRightAssignment_1_0_2; }
		
		//PlusMinusElement
		public RuleCall getRightPlusMinusElementParserRuleCall_1_0_2_0() { return cRightPlusMinusElementParserRuleCall_1_0_2_0; }
		
		//">=" {LargerEqualElement.left=current} right=PlusMinusElement
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//">="
		public Keyword getGreaterThanSignEqualsSignKeyword_1_1_0() { return cGreaterThanSignEqualsSignKeyword_1_1_0; }
		
		//{LargerEqualElement.left=current}
		public Action getLargerEqualElementLeftAction_1_1_1() { return cLargerEqualElementLeftAction_1_1_1; }
		
		//right=PlusMinusElement
		public Assignment getRightAssignment_1_1_2() { return cRightAssignment_1_1_2; }
		
		//PlusMinusElement
		public RuleCall getRightPlusMinusElementParserRuleCall_1_1_2_0() { return cRightPlusMinusElementParserRuleCall_1_1_2_0; }
		
		//"<" {SmallerElement.left=current} right=PlusMinusElement
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//"<"
		public Keyword getLessThanSignKeyword_1_2_0() { return cLessThanSignKeyword_1_2_0; }
		
		//{SmallerElement.left=current}
		public Action getSmallerElementLeftAction_1_2_1() { return cSmallerElementLeftAction_1_2_1; }
		
		//right=PlusMinusElement
		public Assignment getRightAssignment_1_2_2() { return cRightAssignment_1_2_2; }
		
		//PlusMinusElement
		public RuleCall getRightPlusMinusElementParserRuleCall_1_2_2_0() { return cRightPlusMinusElementParserRuleCall_1_2_2_0; }
		
		//"=<" {SmallerEqualElement.left=current} right=PlusMinusElement
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//"=<"
		public Keyword getEqualsSignLessThanSignKeyword_1_3_0() { return cEqualsSignLessThanSignKeyword_1_3_0; }
		
		//{SmallerEqualElement.left=current}
		public Action getSmallerEqualElementLeftAction_1_3_1() { return cSmallerEqualElementLeftAction_1_3_1; }
		
		//right=PlusMinusElement
		public Assignment getRightAssignment_1_3_2() { return cRightAssignment_1_3_2; }
		
		//PlusMinusElement
		public RuleCall getRightPlusMinusElementParserRuleCall_1_3_2_0() { return cRightPlusMinusElementParserRuleCall_1_3_2_0; }
	}
	public class PlusMinusElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.PlusMinusElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplicationDivisionElementParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Action cPlusElementLeftAction_1_0_1 = (Action)cGroup_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cRightMultiplicationDivisionElementParserRuleCall_1_0_2_0 = (RuleCall)cRightAssignment_1_0_2.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Action cMinusElementLeftAction_1_1_1 = (Action)cGroup_1_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cRightMultiplicationDivisionElementParserRuleCall_1_1_2_0 = (RuleCall)cRightAssignment_1_1_2.eContents().get(0);
		
		//PlusMinusElement Element:
		//	MultiplicationDivisionElement ("+" {PlusElement.left=current} right=MultiplicationDivisionElement | "-"
		//	{MinusElement.left=current} right=MultiplicationDivisionElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//MultiplicationDivisionElement ("+" {PlusElement.left=current} right=MultiplicationDivisionElement | "-"
		//{MinusElement.left=current} right=MultiplicationDivisionElement)*
		public Group getGroup() { return cGroup; }
		
		//MultiplicationDivisionElement
		public RuleCall getMultiplicationDivisionElementParserRuleCall_0() { return cMultiplicationDivisionElementParserRuleCall_0; }
		
		//("+" {PlusElement.left=current} right=MultiplicationDivisionElement | "-" {MinusElement.left=current}
		//right=MultiplicationDivisionElement)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"+" {PlusElement.left=current} right=MultiplicationDivisionElement
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//"+"
		public Keyword getPlusSignKeyword_1_0_0() { return cPlusSignKeyword_1_0_0; }
		
		//{PlusElement.left=current}
		public Action getPlusElementLeftAction_1_0_1() { return cPlusElementLeftAction_1_0_1; }
		
		//right=MultiplicationDivisionElement
		public Assignment getRightAssignment_1_0_2() { return cRightAssignment_1_0_2; }
		
		//MultiplicationDivisionElement
		public RuleCall getRightMultiplicationDivisionElementParserRuleCall_1_0_2_0() { return cRightMultiplicationDivisionElementParserRuleCall_1_0_2_0; }
		
		//"-" {MinusElement.left=current} right=MultiplicationDivisionElement
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//"-"
		public Keyword getHyphenMinusKeyword_1_1_0() { return cHyphenMinusKeyword_1_1_0; }
		
		//{MinusElement.left=current}
		public Action getMinusElementLeftAction_1_1_1() { return cMinusElementLeftAction_1_1_1; }
		
		//right=MultiplicationDivisionElement
		public Assignment getRightAssignment_1_1_2() { return cRightAssignment_1_1_2; }
		
		//MultiplicationDivisionElement
		public RuleCall getRightMultiplicationDivisionElementParserRuleCall_1_1_2_0() { return cRightMultiplicationDivisionElementParserRuleCall_1_1_2_0; }
	}
	public class MultiplicationDivisionElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.MultiplicationDivisionElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cUnaryElementParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final Action cMultiplicationElementLeftAction_1_0_1 = (Action)cGroup_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_0_2 = (Assignment)cGroup_1_0.eContents().get(2);
		private final RuleCall cRightUnaryElementParserRuleCall_1_0_2_0 = (RuleCall)cRightAssignment_1_0_2.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cSolidusKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Action cDivisionElementLeftAction_1_1_1 = (Action)cGroup_1_1.eContents().get(1);
		private final Assignment cRightAssignment_1_1_2 = (Assignment)cGroup_1_1.eContents().get(2);
		private final RuleCall cRightUnaryElementParserRuleCall_1_1_2_0 = (RuleCall)cRightAssignment_1_1_2.eContents().get(0);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Keyword cPercentSignKeyword_1_2_0 = (Keyword)cGroup_1_2.eContents().get(0);
		private final Action cModuloElementLeftAction_1_2_1 = (Action)cGroup_1_2.eContents().get(1);
		private final Assignment cRightAssignment_1_2_2 = (Assignment)cGroup_1_2.eContents().get(2);
		private final RuleCall cRightUnaryElementParserRuleCall_1_2_2_0 = (RuleCall)cRightAssignment_1_2_2.eContents().get(0);
		
		//MultiplicationDivisionElement Element:
		//	UnaryElement ("*" {MultiplicationElement.left=current} right=UnaryElement | "/" {DivisionElement.left=current}
		//	right=UnaryElement | "%" {ModuloElement.left=current} right=UnaryElement)*;
		@Override public ParserRule getRule() { return rule; }
		
		//UnaryElement ("*" {MultiplicationElement.left=current} right=UnaryElement | "/" {DivisionElement.left=current}
		//right=UnaryElement | "%" {ModuloElement.left=current} right=UnaryElement)*
		public Group getGroup() { return cGroup; }
		
		//UnaryElement
		public RuleCall getUnaryElementParserRuleCall_0() { return cUnaryElementParserRuleCall_0; }
		
		//("*" {MultiplicationElement.left=current} right=UnaryElement | "/" {DivisionElement.left=current} right=UnaryElement |
		//"%" {ModuloElement.left=current} right=UnaryElement)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//"*" {MultiplicationElement.left=current} right=UnaryElement
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//"*"
		public Keyword getAsteriskKeyword_1_0_0() { return cAsteriskKeyword_1_0_0; }
		
		//{MultiplicationElement.left=current}
		public Action getMultiplicationElementLeftAction_1_0_1() { return cMultiplicationElementLeftAction_1_0_1; }
		
		//right=UnaryElement
		public Assignment getRightAssignment_1_0_2() { return cRightAssignment_1_0_2; }
		
		//UnaryElement
		public RuleCall getRightUnaryElementParserRuleCall_1_0_2_0() { return cRightUnaryElementParserRuleCall_1_0_2_0; }
		
		//"/" {DivisionElement.left=current} right=UnaryElement
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//"/"
		public Keyword getSolidusKeyword_1_1_0() { return cSolidusKeyword_1_1_0; }
		
		//{DivisionElement.left=current}
		public Action getDivisionElementLeftAction_1_1_1() { return cDivisionElementLeftAction_1_1_1; }
		
		//right=UnaryElement
		public Assignment getRightAssignment_1_1_2() { return cRightAssignment_1_1_2; }
		
		//UnaryElement
		public RuleCall getRightUnaryElementParserRuleCall_1_1_2_0() { return cRightUnaryElementParserRuleCall_1_1_2_0; }
		
		//"%" {ModuloElement.left=current} right=UnaryElement
		public Group getGroup_1_2() { return cGroup_1_2; }
		
		//"%"
		public Keyword getPercentSignKeyword_1_2_0() { return cPercentSignKeyword_1_2_0; }
		
		//{ModuloElement.left=current}
		public Action getModuloElementLeftAction_1_2_1() { return cModuloElementLeftAction_1_2_1; }
		
		//right=UnaryElement
		public Assignment getRightAssignment_1_2_2() { return cRightAssignment_1_2_2; }
		
		//UnaryElement
		public RuleCall getRightUnaryElementParserRuleCall_1_2_2_0() { return cRightUnaryElementParserRuleCall_1_2_2_0; }
	}
	public class UnaryElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.UnaryElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cNumber_ObjectAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueNUMBERParserRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cBoolean_ObjectAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cValueAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cValueBOOLEANTerminalRuleCall_1_1_0 = (RuleCall)cValueAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cResource_ObjectAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cValueAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cValueResourceCrossReference_2_1_0 = (CrossReference)cValueAssignment_2_1.eContents().get(0);
		private final RuleCall cValueResourceIDTerminalRuleCall_2_1_0_1 = (RuleCall)cValueResourceCrossReference_2_1_0.eContents().get(1);
		private final Keyword cStateKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cState_ObjectAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final Assignment cValueAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValueStateParserRuleCall_3_1_0 = (RuleCall)cValueAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cAlternatives.eContents().get(4);
		private final Keyword cLeftParenthesisKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final RuleCall cOrElementParserRuleCall_4_1 = (RuleCall)cGroup_4.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_2 = (Keyword)cGroup_4.eContents().get(2);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Keyword cNotKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Action cNegateElementAction_5_1 = (Action)cGroup_5.eContents().get(1);
		private final Assignment cExpAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cExpUnaryElementParserRuleCall_5_2_0 = (RuleCall)cExpAssignment_5_2.eContents().get(0);
		
		////TO-DO  more thinking here about the UnaryElement...
		////	{String_Object} value=EXTENDED_STRING |
		//UnaryElement Element:
		//	{Number_Object} value=NUMBER | {Boolean_Object} value=BOOLEAN | {Resource_Object} value=[Resource] ".state" |
		//	{State_Object} value=State |
		//	"(" OrElement ")" |
		//	"not" {NegateElement} exp=UnaryElement;
		@Override public ParserRule getRule() { return rule; }
		
		//{Number_Object} value=NUMBER | {Boolean_Object} value=BOOLEAN | {Resource_Object} value=[Resource] ".state" |
		//{State_Object} value=State | "(" OrElement ")" | "not" {NegateElement} exp=UnaryElement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{Number_Object} value=NUMBER
		public Group getGroup_0() { return cGroup_0; }
		
		//{Number_Object}
		public Action getNumber_ObjectAction_0_0() { return cNumber_ObjectAction_0_0; }
		
		//value=NUMBER
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }
		
		//NUMBER
		public RuleCall getValueNUMBERParserRuleCall_0_1_0() { return cValueNUMBERParserRuleCall_0_1_0; }
		
		//{Boolean_Object} value=BOOLEAN
		public Group getGroup_1() { return cGroup_1; }
		
		//{Boolean_Object}
		public Action getBoolean_ObjectAction_1_0() { return cBoolean_ObjectAction_1_0; }
		
		//value=BOOLEAN
		public Assignment getValueAssignment_1_1() { return cValueAssignment_1_1; }
		
		//BOOLEAN
		public RuleCall getValueBOOLEANTerminalRuleCall_1_1_0() { return cValueBOOLEANTerminalRuleCall_1_1_0; }
		
		//{Resource_Object} value=[Resource] ".state"
		public Group getGroup_2() { return cGroup_2; }
		
		//{Resource_Object}
		public Action getResource_ObjectAction_2_0() { return cResource_ObjectAction_2_0; }
		
		//value=[Resource]
		public Assignment getValueAssignment_2_1() { return cValueAssignment_2_1; }
		
		//[Resource]
		public CrossReference getValueResourceCrossReference_2_1_0() { return cValueResourceCrossReference_2_1_0; }
		
		//ID
		public RuleCall getValueResourceIDTerminalRuleCall_2_1_0_1() { return cValueResourceIDTerminalRuleCall_2_1_0_1; }
		
		//".state"
		public Keyword getStateKeyword_2_2() { return cStateKeyword_2_2; }
		
		//{State_Object} value=State
		public Group getGroup_3() { return cGroup_3; }
		
		//{State_Object}
		public Action getState_ObjectAction_3_0() { return cState_ObjectAction_3_0; }
		
		//value=State
		public Assignment getValueAssignment_3_1() { return cValueAssignment_3_1; }
		
		//State
		public RuleCall getValueStateParserRuleCall_3_1_0() { return cValueStateParserRuleCall_3_1_0; }
		
		//"(" OrElement ")"
		public Group getGroup_4() { return cGroup_4; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_4_0() { return cLeftParenthesisKeyword_4_0; }
		
		//OrElement
		public RuleCall getOrElementParserRuleCall_4_1() { return cOrElementParserRuleCall_4_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_4_2() { return cRightParenthesisKeyword_4_2; }
		
		//"not" {NegateElement} exp=UnaryElement
		public Group getGroup_5() { return cGroup_5; }
		
		//"not"
		public Keyword getNotKeyword_5_0() { return cNotKeyword_5_0; }
		
		//{NegateElement}
		public Action getNegateElementAction_5_1() { return cNegateElementAction_5_1; }
		
		//exp=UnaryElement
		public Assignment getExpAssignment_5_2() { return cExpAssignment_5_2; }
		
		//UnaryElement
		public RuleCall getExpUnaryElementParserRuleCall_5_2_0() { return cExpUnaryElementParserRuleCall_5_2_0; }
	}
	public class LBRACEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.LBRACE");
		private final Keyword cLeftCurlyBracketKeyword = (Keyword)rule.eContents().get(1);
		
		//LBRACE:
		//	"{";
		@Override public ParserRule getRule() { return rule; }
		
		//"{"
		public Keyword getLeftCurlyBracketKeyword() { return cLeftCurlyBracketKeyword; }
	}
	public class RBRACEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.RBRACE");
		private final Keyword cRightCurlyBracketKeyword = (Keyword)rule.eContents().get(1);
		
		//RBRACE:
		//	"}";
		@Override public ParserRule getRule() { return rule; }
		
		//"}"
		public Keyword getRightCurlyBracketKeyword() { return cRightCurlyBracketKeyword; }
	}
	public class NUMBERElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.NUMBER");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Keyword cFullStopKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		
		//NUMBER ecore::EBigDecimal:
		//	INT | INT '.' INT;
		@Override public ParserRule getRule() { return rule; }
		
		//INT | INT '.' INT
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//INT '.' INT
		public Group getGroup_1() { return cGroup_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_0() { return cINTTerminalRuleCall_1_0; }
		
		//'.'
		public Keyword getFullStopKeyword_1_1() { return cFullStopKeyword_1_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1_2() { return cINTTerminalRuleCall_1_2; }
	}
	public class EXTENDED_IDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.EXTENDED_ID");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//EXTENDED_ID:
		//	ID ('.' ID)*;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)*
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	public class EXTENDED_STRINGElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.EXTENDED_STRING");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		
		//EXTENDED_STRING:
		//	ID ('.' ID)* ('(' ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//ID ('.' ID)* ('(' ')')?
		public Group getGroup() { return cGroup; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }
		
		//('.' ID)*
		public Group getGroup_1() { return cGroup_1; }
		
		//'.'
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
		
		//('(' ')')?
		public Group getGroup_2() { return cGroup_2; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2_1() { return cRightParenthesisKeyword_2_1; }
	}
	
	
	private final RunTimeModelElements pRunTimeModel;
	private final StateElements pState;
	private final ResourceElements pResource;
	private final AppMetaDataElements pAppMetaData;
	private final SpecificationElements pSpecification;
	private final TriggerElements pTrigger;
	private final IfDoSpecElements pIfDoSpec;
	private final ElseIfDoSpecElements pElseIfDoSpec;
	private final ElseDoSpecElements pElseDoSpec;
	private final EnvironmentMetaDataElements pEnvironmentMetaData;
	private final ActionElements pAction;
	private final OrElementElements pOrElement;
	private final AndElementElements pAndElement;
	private final DiffEqualElementElements pDiffEqualElement;
	private final CompareElementElements pCompareElement;
	private final PlusMinusElementElements pPlusMinusElement;
	private final MultiplicationDivisionElementElements pMultiplicationDivisionElement;
	private final UnaryElementElements pUnaryElement;
	private final LBRACEElements pLBRACE;
	private final RBRACEElements pRBRACE;
	private final TerminalRule tBOOLEAN;
	private final TerminalRule tINT;
	private final NUMBERElements pNUMBER;
	private final TerminalRule tID;
	private final EXTENDED_IDElements pEXTENDED_ID;
	private final EXTENDED_STRINGElements pEXTENDED_STRING;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public DslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pRunTimeModel = new RunTimeModelElements();
		this.pState = new StateElements();
		this.pResource = new ResourceElements();
		this.pAppMetaData = new AppMetaDataElements();
		this.pSpecification = new SpecificationElements();
		this.pTrigger = new TriggerElements();
		this.pIfDoSpec = new IfDoSpecElements();
		this.pElseIfDoSpec = new ElseIfDoSpecElements();
		this.pElseDoSpec = new ElseDoSpecElements();
		this.pEnvironmentMetaData = new EnvironmentMetaDataElements();
		this.pAction = new ActionElements();
		this.pOrElement = new OrElementElements();
		this.pAndElement = new AndElementElements();
		this.pDiffEqualElement = new DiffEqualElementElements();
		this.pCompareElement = new CompareElementElements();
		this.pPlusMinusElement = new PlusMinusElementElements();
		this.pMultiplicationDivisionElement = new MultiplicationDivisionElementElements();
		this.pUnaryElement = new UnaryElementElements();
		this.pLBRACE = new LBRACEElements();
		this.pRBRACE = new RBRACEElements();
		this.tBOOLEAN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.BOOLEAN");
		this.tINT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.INT");
		this.pNUMBER = new NUMBERElements();
		this.tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "nii.bigclout.ecaadapter.Dsl.ID");
		this.pEXTENDED_ID = new EXTENDED_IDElements();
		this.pEXTENDED_STRING = new EXTENDED_STRINGElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("nii.bigclout.ecaadapter.Dsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//RunTimeModel:
	//	{RunTimeModel} envData+=EnvironmentMetaData
	//	appData+=AppMetaData;
	public RunTimeModelElements getRunTimeModelAccess() {
		return pRunTimeModel;
	}
	
	public ParserRule getRunTimeModelRule() {
		return getRunTimeModelAccess().getRule();
	}
	
	//State:
	//	name=ID;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}
	
	//Resource:
	//	"resource" name=ID ("can" "be" states+=State ("," states+=State)*)?;
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}
	
	//AppMetaData:
	//	"app" appID=ID
	//	LBRACE
	//	specification=Specification
	//	RBRACE;
	public AppMetaDataElements getAppMetaDataAccess() {
		return pAppMetaData;
	}
	
	public ParserRule getAppMetaDataRule() {
		return getAppMetaDataAccess().getRule();
	}
	
	//Specification:
	//	specID=ID? ('priority' priority=INT)?
	//	'on' trigger+=Trigger ("," trigger+=Trigger)*
	//	ifdo=IfDoSpec
	//	elseIfDo+=ElseIfDoSpec*
	//	elseDo=ElseDoSpec?;
	public SpecificationElements getSpecificationAccess() {
		return pSpecification;
	}
	
	public ParserRule getSpecificationRule() {
		return getSpecificationAccess().getRule();
	}
	
	//Trigger:
	//	resource=[Resource] ("is" | "are") state=State;
	public TriggerElements getTriggerAccess() {
		return pTrigger;
	}
	
	public ParserRule getTriggerRule() {
		return getTriggerAccess().getRule();
	}
	
	//IfDoSpec:
	//	'if' condition=OrElement 'do' action+=Action ("and" action+=Action)*;
	public IfDoSpecElements getIfDoSpecAccess() {
		return pIfDoSpec;
	}
	
	public ParserRule getIfDoSpecRule() {
		return getIfDoSpecAccess().getRule();
	}
	
	//ElseIfDoSpec:
	//	'else' 'if' condition=OrElement 'do' action+=Action ("and" action+=Action)*;
	public ElseIfDoSpecElements getElseIfDoSpecAccess() {
		return pElseIfDoSpec;
	}
	
	public ParserRule getElseIfDoSpecRule() {
		return getElseIfDoSpecAccess().getRule();
	}
	
	//ElseDoSpec:
	//	'else' 'do' action+=Action ("and" action+=Action)*;
	public ElseDoSpecElements getElseDoSpecAccess() {
		return pElseDoSpec;
	}
	
	public ParserRule getElseDoSpecRule() {
		return getElseDoSpecAccess().getRule();
	}
	
	//EnvironmentMetaData:
	//	{EnvironmentMetaData}
	//	"environment"
	//	LBRACE
	//	resources+=Resource+
	//	// maybe some specification that apply globally....
	//	RBRACE;
	public EnvironmentMetaDataElements getEnvironmentMetaDataAccess() {
		return pEnvironmentMetaData;
	}
	
	public ParserRule getEnvironmentMetaDataRule() {
		return getEnvironmentMetaDataAccess().getRule();
	}
	
	//Action:
	//	resource=[Resource] ":=" state=State;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//OrElement Element:
	//	AndElement ("or" {OrElement.left=current} right=AndElement)*;
	public OrElementElements getOrElementAccess() {
		return pOrElement;
	}
	
	public ParserRule getOrElementRule() {
		return getOrElementAccess().getRule();
	}
	
	//AndElement Element:
	//	DiffEqualElement ("and" {AndElement.left=current} right=DiffEqualElement)*;
	public AndElementElements getAndElementAccess() {
		return pAndElement;
	}
	
	public ParserRule getAndElementRule() {
		return getAndElementAccess().getRule();
	}
	
	//DiffEqualElement Element:
	//	CompareElement ("!=" {DiffElement.left=current} right=CompareElement | "==" {EqualElement.left=current}
	//	right=CompareElement)*;
	public DiffEqualElementElements getDiffEqualElementAccess() {
		return pDiffEqualElement;
	}
	
	public ParserRule getDiffEqualElementRule() {
		return getDiffEqualElementAccess().getRule();
	}
	
	//CompareElement Element:
	//	PlusMinusElement (">" {LargerElement.left=current} right=PlusMinusElement | ">=" {LargerEqualElement.left=current}
	//	right=PlusMinusElement | "<" {SmallerElement.left=current} right=PlusMinusElement | "=<"
	//	{SmallerEqualElement.left=current} right=PlusMinusElement)*;
	public CompareElementElements getCompareElementAccess() {
		return pCompareElement;
	}
	
	public ParserRule getCompareElementRule() {
		return getCompareElementAccess().getRule();
	}
	
	//PlusMinusElement Element:
	//	MultiplicationDivisionElement ("+" {PlusElement.left=current} right=MultiplicationDivisionElement | "-"
	//	{MinusElement.left=current} right=MultiplicationDivisionElement)*;
	public PlusMinusElementElements getPlusMinusElementAccess() {
		return pPlusMinusElement;
	}
	
	public ParserRule getPlusMinusElementRule() {
		return getPlusMinusElementAccess().getRule();
	}
	
	//MultiplicationDivisionElement Element:
	//	UnaryElement ("*" {MultiplicationElement.left=current} right=UnaryElement | "/" {DivisionElement.left=current}
	//	right=UnaryElement | "%" {ModuloElement.left=current} right=UnaryElement)*;
	public MultiplicationDivisionElementElements getMultiplicationDivisionElementAccess() {
		return pMultiplicationDivisionElement;
	}
	
	public ParserRule getMultiplicationDivisionElementRule() {
		return getMultiplicationDivisionElementAccess().getRule();
	}
	
	////TO-DO  more thinking here about the UnaryElement...
	////	{String_Object} value=EXTENDED_STRING |
	//UnaryElement Element:
	//	{Number_Object} value=NUMBER | {Boolean_Object} value=BOOLEAN | {Resource_Object} value=[Resource] ".state" |
	//	{State_Object} value=State |
	//	"(" OrElement ")" |
	//	"not" {NegateElement} exp=UnaryElement;
	public UnaryElementElements getUnaryElementAccess() {
		return pUnaryElement;
	}
	
	public ParserRule getUnaryElementRule() {
		return getUnaryElementAccess().getRule();
	}
	
	//LBRACE:
	//	"{";
	public LBRACEElements getLBRACEAccess() {
		return pLBRACE;
	}
	
	public ParserRule getLBRACERule() {
		return getLBRACEAccess().getRule();
	}
	
	//RBRACE:
	//	"}";
	public RBRACEElements getRBRACEAccess() {
		return pRBRACE;
	}
	
	public ParserRule getRBRACERule() {
		return getRBRACEAccess().getRule();
	}
	
	//terminal BOOLEAN returns ecore::EBoolean:
	//	'true' | 'false';
	public TerminalRule getBOOLEANRule() {
		return tBOOLEAN;
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return tINT;
	}
	
	//NUMBER ecore::EBigDecimal:
	//	INT | INT '.' INT;
	public NUMBERElements getNUMBERAccess() {
		return pNUMBER;
	}
	
	public ParserRule getNUMBERRule() {
		return getNUMBERAccess().getRule();
	}
	
	//terminal ID:
	//	'a'..'z' | 'A'..'Z' | '_' | '0'..'9' | ':' | '-'+;
	public TerminalRule getIDRule() {
		return tID;
	}
	
	//EXTENDED_ID:
	//	ID ('.' ID)*;
	public EXTENDED_IDElements getEXTENDED_IDAccess() {
		return pEXTENDED_ID;
	}
	
	public ParserRule getEXTENDED_IDRule() {
		return getEXTENDED_IDAccess().getRule();
	}
	
	//EXTENDED_STRING:
	//	ID ('.' ID)* ('(' ')')?;
	public EXTENDED_STRINGElements getEXTENDED_STRINGAccess() {
		return pEXTENDED_STRING;
	}
	
	public ParserRule getEXTENDED_STRINGRule() {
		return getEXTENDED_STRINGAccess().getRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' | "'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
