/**
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.dsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see nii.bigclout.ecaadapter.dsl.DslFactory
 * @model kind="package"
 * @generated
 */
public interface DslPackage extends EPackage
{
  /**
	 * The package name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNAME = "dsl";

  /**
	 * The package namespace URI.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_URI = "http://www.bigclout.nii/ecaadapter/Dsl";

  /**
	 * The package namespace name.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  String eNS_PREFIX = "dsl";

  /**
	 * The singleton instance of the package.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  DslPackage eINSTANCE = nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl.init();

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.RunTimeModelImpl <em>Run Time Model</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.RunTimeModelImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getRunTimeModel()
	 * @generated
	 */
  int RUN_TIME_MODEL = 0;

  /**
	 * The feature id for the '<em><b>Env Data</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RUN_TIME_MODEL__ENV_DATA = 0;

  /**
	 * The feature id for the '<em><b>App Data</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RUN_TIME_MODEL__APP_DATA = 1;

  /**
	 * The number of structural features of the '<em>Run Time Model</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RUN_TIME_MODEL_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.StateImpl <em>State</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.StateImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getState()
	 * @generated
	 */
  int STATE = 1;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int STATE__NAME = 0;

  /**
	 * The number of structural features of the '<em>State</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int STATE_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.ResourceImpl <em>Resource</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.ResourceImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getResource()
	 * @generated
	 */
  int RESOURCE = 2;

  /**
	 * The feature id for the '<em><b>Name</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RESOURCE__NAME = 0;

  /**
	 * The feature id for the '<em><b>States</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RESOURCE__STATES = 1;

  /**
	 * The number of structural features of the '<em>Resource</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RESOURCE_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.AppMetaDataImpl <em>App Meta Data</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.AppMetaDataImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getAppMetaData()
	 * @generated
	 */
  int APP_META_DATA = 3;

  /**
	 * The feature id for the '<em><b>App ID</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int APP_META_DATA__APP_ID = 0;

  /**
	 * The feature id for the '<em><b>Specification</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int APP_META_DATA__SPECIFICATION = 1;

  /**
	 * The number of structural features of the '<em>App Meta Data</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int APP_META_DATA_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.SpecificationImpl <em>Specification</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.SpecificationImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getSpecification()
	 * @generated
	 */
  int SPECIFICATION = 4;

  /**
	 * The feature id for the '<em><b>Spec ID</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION__SPEC_ID = 0;

  /**
	 * The feature id for the '<em><b>Priority</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION__PRIORITY = 1;

  /**
	 * The feature id for the '<em><b>Trigger</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION__TRIGGER = 2;

  /**
	 * The feature id for the '<em><b>Ifdo</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION__IFDO = 3;

  /**
	 * The feature id for the '<em><b>Else If Do</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION__ELSE_IF_DO = 4;

  /**
	 * The feature id for the '<em><b>Else Do</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION__ELSE_DO = 5;

  /**
	 * The number of structural features of the '<em>Specification</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SPECIFICATION_FEATURE_COUNT = 6;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.TriggerImpl <em>Trigger</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.TriggerImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getTrigger()
	 * @generated
	 */
  int TRIGGER = 5;

  /**
	 * The feature id for the '<em><b>Resource</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TRIGGER__RESOURCE = 0;

  /**
	 * The feature id for the '<em><b>State</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TRIGGER__STATE = 1;

  /**
	 * The number of structural features of the '<em>Trigger</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int TRIGGER_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.IfDoSpecImpl <em>If Do Spec</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.IfDoSpecImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getIfDoSpec()
	 * @generated
	 */
  int IF_DO_SPEC = 6;

  /**
	 * The feature id for the '<em><b>Condition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int IF_DO_SPEC__CONDITION = 0;

  /**
	 * The feature id for the '<em><b>Action</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int IF_DO_SPEC__ACTION = 1;

  /**
	 * The number of structural features of the '<em>If Do Spec</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int IF_DO_SPEC_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.ElseIfDoSpecImpl <em>Else If Do Spec</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.ElseIfDoSpecImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getElseIfDoSpec()
	 * @generated
	 */
  int ELSE_IF_DO_SPEC = 7;

  /**
	 * The feature id for the '<em><b>Condition</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ELSE_IF_DO_SPEC__CONDITION = 0;

  /**
	 * The feature id for the '<em><b>Action</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ELSE_IF_DO_SPEC__ACTION = 1;

  /**
	 * The number of structural features of the '<em>Else If Do Spec</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ELSE_IF_DO_SPEC_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.ElseDoSpecImpl <em>Else Do Spec</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.ElseDoSpecImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getElseDoSpec()
	 * @generated
	 */
  int ELSE_DO_SPEC = 8;

  /**
	 * The feature id for the '<em><b>Action</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ELSE_DO_SPEC__ACTION = 0;

  /**
	 * The number of structural features of the '<em>Else Do Spec</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ELSE_DO_SPEC_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.EnvironmentMetaDataImpl <em>Environment Meta Data</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.EnvironmentMetaDataImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getEnvironmentMetaData()
	 * @generated
	 */
  int ENVIRONMENT_META_DATA = 9;

  /**
	 * The feature id for the '<em><b>Resources</b></em>' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENVIRONMENT_META_DATA__RESOURCES = 0;

  /**
	 * The number of structural features of the '<em>Environment Meta Data</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ENVIRONMENT_META_DATA_FEATURE_COUNT = 1;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.ActionImpl <em>Action</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.ActionImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getAction()
	 * @generated
	 */
  int ACTION = 10;

  /**
	 * The feature id for the '<em><b>Resource</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTION__RESOURCE = 0;

  /**
	 * The feature id for the '<em><b>State</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTION__STATE = 1;

  /**
	 * The number of structural features of the '<em>Action</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ACTION_FEATURE_COUNT = 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.ElementImpl <em>Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.ElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getElement()
	 * @generated
	 */
  int ELEMENT = 11;

  /**
	 * The number of structural features of the '<em>Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.OrElementImpl <em>Or Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.OrElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getOrElement()
	 * @generated
	 */
  int OR_ELEMENT = 12;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OR_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OR_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Or Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int OR_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.AndElementImpl <em>And Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.AndElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getAndElement()
	 * @generated
	 */
  int AND_ELEMENT = 13;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int AND_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int AND_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>And Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int AND_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.DiffElementImpl <em>Diff Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.DiffElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getDiffElement()
	 * @generated
	 */
  int DIFF_ELEMENT = 14;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DIFF_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DIFF_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Diff Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DIFF_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.EqualElementImpl <em>Equal Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.EqualElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getEqualElement()
	 * @generated
	 */
  int EQUAL_ELEMENT = 15;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int EQUAL_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int EQUAL_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Equal Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int EQUAL_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.LargerElementImpl <em>Larger Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.LargerElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getLargerElement()
	 * @generated
	 */
  int LARGER_ELEMENT = 16;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LARGER_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LARGER_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Larger Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LARGER_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.LargerEqualElementImpl <em>Larger Equal Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.LargerEqualElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getLargerEqualElement()
	 * @generated
	 */
  int LARGER_EQUAL_ELEMENT = 17;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LARGER_EQUAL_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LARGER_EQUAL_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Larger Equal Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int LARGER_EQUAL_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.SmallerElementImpl <em>Smaller Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.SmallerElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getSmallerElement()
	 * @generated
	 */
  int SMALLER_ELEMENT = 18;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SMALLER_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SMALLER_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Smaller Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SMALLER_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.SmallerEqualElementImpl <em>Smaller Equal Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.SmallerEqualElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getSmallerEqualElement()
	 * @generated
	 */
  int SMALLER_EQUAL_ELEMENT = 19;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SMALLER_EQUAL_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SMALLER_EQUAL_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Smaller Equal Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int SMALLER_EQUAL_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.PlusElementImpl <em>Plus Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.PlusElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getPlusElement()
	 * @generated
	 */
  int PLUS_ELEMENT = 20;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int PLUS_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int PLUS_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Plus Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int PLUS_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.MinusElementImpl <em>Minus Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.MinusElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getMinusElement()
	 * @generated
	 */
  int MINUS_ELEMENT = 21;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MINUS_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MINUS_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Minus Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MINUS_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.MultiplicationElementImpl <em>Multiplication Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.MultiplicationElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getMultiplicationElement()
	 * @generated
	 */
  int MULTIPLICATION_ELEMENT = 22;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MULTIPLICATION_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MULTIPLICATION_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Multiplication Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MULTIPLICATION_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.DivisionElementImpl <em>Division Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.DivisionElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getDivisionElement()
	 * @generated
	 */
  int DIVISION_ELEMENT = 23;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DIVISION_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DIVISION_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Division Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int DIVISION_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.ModuloElementImpl <em>Modulo Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.ModuloElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getModuloElement()
	 * @generated
	 */
  int MODULO_ELEMENT = 24;

  /**
	 * The feature id for the '<em><b>Left</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MODULO_ELEMENT__LEFT = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The feature id for the '<em><b>Right</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MODULO_ELEMENT__RIGHT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The number of structural features of the '<em>Modulo Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int MODULO_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 2;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.Number_ObjectImpl <em>Number Object</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.Number_ObjectImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getNumber_Object()
	 * @generated
	 */
  int NUMBER_OBJECT = 25;

  /**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int NUMBER_OBJECT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>Number Object</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int NUMBER_OBJECT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.Boolean_ObjectImpl <em>Boolean Object</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.Boolean_ObjectImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getBoolean_Object()
	 * @generated
	 */
  int BOOLEAN_OBJECT = 26;

  /**
	 * The feature id for the '<em><b>Value</b></em>' attribute.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int BOOLEAN_OBJECT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>Boolean Object</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int BOOLEAN_OBJECT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.Resource_ObjectImpl <em>Resource Object</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.Resource_ObjectImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getResource_Object()
	 * @generated
	 */
  int RESOURCE_OBJECT = 27;

  /**
	 * The feature id for the '<em><b>Value</b></em>' reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RESOURCE_OBJECT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>Resource Object</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int RESOURCE_OBJECT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.State_ObjectImpl <em>State Object</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.State_ObjectImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getState_Object()
	 * @generated
	 */
  int STATE_OBJECT = 28;

  /**
	 * The feature id for the '<em><b>Value</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int STATE_OBJECT__VALUE = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>State Object</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int STATE_OBJECT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;

  /**
	 * The meta object id for the '{@link nii.bigclout.ecaadapter.dsl.impl.NegateElementImpl <em>Negate Element</em>}' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see nii.bigclout.ecaadapter.dsl.impl.NegateElementImpl
	 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getNegateElement()
	 * @generated
	 */
  int NEGATE_ELEMENT = 29;

  /**
	 * The feature id for the '<em><b>Exp</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int NEGATE_ELEMENT__EXP = ELEMENT_FEATURE_COUNT + 0;

  /**
	 * The number of structural features of the '<em>Negate Element</em>' class.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 * @ordered
	 */
  int NEGATE_ELEMENT_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;


  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.RunTimeModel <em>Run Time Model</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Run Time Model</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.RunTimeModel
	 * @generated
	 */
  EClass getRunTimeModel();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.RunTimeModel#getEnvData <em>Env Data</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Env Data</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.RunTimeModel#getEnvData()
	 * @see #getRunTimeModel()
	 * @generated
	 */
  EReference getRunTimeModel_EnvData();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.RunTimeModel#getAppData <em>App Data</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>App Data</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.RunTimeModel#getAppData()
	 * @see #getRunTimeModel()
	 * @generated
	 */
  EReference getRunTimeModel_AppData();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.State <em>State</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>State</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.State
	 * @generated
	 */
  EClass getState();

  /**
	 * Returns the meta object for the attribute '{@link nii.bigclout.ecaadapter.dsl.State#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.State#getName()
	 * @see #getState()
	 * @generated
	 */
  EAttribute getState_Name();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Resource <em>Resource</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Resource</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Resource
	 * @generated
	 */
  EClass getResource();

  /**
	 * Returns the meta object for the attribute '{@link nii.bigclout.ecaadapter.dsl.Resource#getName <em>Name</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Name</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Resource#getName()
	 * @see #getResource()
	 * @generated
	 */
  EAttribute getResource_Name();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.Resource#getStates <em>States</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>States</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Resource#getStates()
	 * @see #getResource()
	 * @generated
	 */
  EReference getResource_States();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.AppMetaData <em>App Meta Data</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>App Meta Data</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.AppMetaData
	 * @generated
	 */
  EClass getAppMetaData();

  /**
	 * Returns the meta object for the attribute '{@link nii.bigclout.ecaadapter.dsl.AppMetaData#getAppID <em>App ID</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>App ID</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.AppMetaData#getAppID()
	 * @see #getAppMetaData()
	 * @generated
	 */
  EAttribute getAppMetaData_AppID();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.AppMetaData#getSpecification <em>Specification</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Specification</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.AppMetaData#getSpecification()
	 * @see #getAppMetaData()
	 * @generated
	 */
  EReference getAppMetaData_Specification();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Specification <em>Specification</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Specification</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Specification
	 * @generated
	 */
  EClass getSpecification();

  /**
	 * Returns the meta object for the attribute '{@link nii.bigclout.ecaadapter.dsl.Specification#getSpecID <em>Spec ID</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Spec ID</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Specification#getSpecID()
	 * @see #getSpecification()
	 * @generated
	 */
  EAttribute getSpecification_SpecID();

  /**
	 * Returns the meta object for the attribute '{@link nii.bigclout.ecaadapter.dsl.Specification#getPriority <em>Priority</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Priority</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Specification#getPriority()
	 * @see #getSpecification()
	 * @generated
	 */
  EAttribute getSpecification_Priority();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.Specification#getTrigger <em>Trigger</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Trigger</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Specification#getTrigger()
	 * @see #getSpecification()
	 * @generated
	 */
  EReference getSpecification_Trigger();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.Specification#getIfdo <em>Ifdo</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Ifdo</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Specification#getIfdo()
	 * @see #getSpecification()
	 * @generated
	 */
  EReference getSpecification_Ifdo();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.Specification#getElseIfDo <em>Else If Do</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Else If Do</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Specification#getElseIfDo()
	 * @see #getSpecification()
	 * @generated
	 */
  EReference getSpecification_ElseIfDo();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.Specification#getElseDo <em>Else Do</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Else Do</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Specification#getElseDo()
	 * @see #getSpecification()
	 * @generated
	 */
  EReference getSpecification_ElseDo();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Trigger <em>Trigger</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Trigger</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Trigger
	 * @generated
	 */
  EClass getTrigger();

  /**
	 * Returns the meta object for the reference '{@link nii.bigclout.ecaadapter.dsl.Trigger#getResource <em>Resource</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Resource</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Trigger#getResource()
	 * @see #getTrigger()
	 * @generated
	 */
  EReference getTrigger_Resource();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.Trigger#getState <em>State</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>State</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Trigger#getState()
	 * @see #getTrigger()
	 * @generated
	 */
  EReference getTrigger_State();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.IfDoSpec <em>If Do Spec</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>If Do Spec</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.IfDoSpec
	 * @generated
	 */
  EClass getIfDoSpec();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.IfDoSpec#getCondition <em>Condition</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Condition</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.IfDoSpec#getCondition()
	 * @see #getIfDoSpec()
	 * @generated
	 */
  EReference getIfDoSpec_Condition();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.IfDoSpec#getAction <em>Action</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Action</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.IfDoSpec#getAction()
	 * @see #getIfDoSpec()
	 * @generated
	 */
  EReference getIfDoSpec_Action();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.ElseIfDoSpec <em>Else If Do Spec</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Else If Do Spec</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ElseIfDoSpec
	 * @generated
	 */
  EClass getElseIfDoSpec();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.ElseIfDoSpec#getCondition <em>Condition</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Condition</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ElseIfDoSpec#getCondition()
	 * @see #getElseIfDoSpec()
	 * @generated
	 */
  EReference getElseIfDoSpec_Condition();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.ElseIfDoSpec#getAction <em>Action</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Action</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ElseIfDoSpec#getAction()
	 * @see #getElseIfDoSpec()
	 * @generated
	 */
  EReference getElseIfDoSpec_Action();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.ElseDoSpec <em>Else Do Spec</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Else Do Spec</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ElseDoSpec
	 * @generated
	 */
  EClass getElseDoSpec();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.ElseDoSpec#getAction <em>Action</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Action</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ElseDoSpec#getAction()
	 * @see #getElseDoSpec()
	 * @generated
	 */
  EReference getElseDoSpec_Action();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.EnvironmentMetaData <em>Environment Meta Data</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Environment Meta Data</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.EnvironmentMetaData
	 * @generated
	 */
  EClass getEnvironmentMetaData();

  /**
	 * Returns the meta object for the containment reference list '{@link nii.bigclout.ecaadapter.dsl.EnvironmentMetaData#getResources <em>Resources</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference list '<em>Resources</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.EnvironmentMetaData#getResources()
	 * @see #getEnvironmentMetaData()
	 * @generated
	 */
  EReference getEnvironmentMetaData_Resources();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Action <em>Action</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Action</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Action
	 * @generated
	 */
  EClass getAction();

  /**
	 * Returns the meta object for the reference '{@link nii.bigclout.ecaadapter.dsl.Action#getResource <em>Resource</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Resource</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Action#getResource()
	 * @see #getAction()
	 * @generated
	 */
  EReference getAction_Resource();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.Action#getState <em>State</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>State</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Action#getState()
	 * @see #getAction()
	 * @generated
	 */
  EReference getAction_State();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Element <em>Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Element
	 * @generated
	 */
  EClass getElement();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.OrElement <em>Or Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Or Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.OrElement
	 * @generated
	 */
  EClass getOrElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.OrElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.OrElement#getLeft()
	 * @see #getOrElement()
	 * @generated
	 */
  EReference getOrElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.OrElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.OrElement#getRight()
	 * @see #getOrElement()
	 * @generated
	 */
  EReference getOrElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.AndElement <em>And Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>And Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.AndElement
	 * @generated
	 */
  EClass getAndElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.AndElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.AndElement#getLeft()
	 * @see #getAndElement()
	 * @generated
	 */
  EReference getAndElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.AndElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.AndElement#getRight()
	 * @see #getAndElement()
	 * @generated
	 */
  EReference getAndElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.DiffElement <em>Diff Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Diff Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.DiffElement
	 * @generated
	 */
  EClass getDiffElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.DiffElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.DiffElement#getLeft()
	 * @see #getDiffElement()
	 * @generated
	 */
  EReference getDiffElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.DiffElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.DiffElement#getRight()
	 * @see #getDiffElement()
	 * @generated
	 */
  EReference getDiffElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.EqualElement <em>Equal Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Equal Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.EqualElement
	 * @generated
	 */
  EClass getEqualElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.EqualElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.EqualElement#getLeft()
	 * @see #getEqualElement()
	 * @generated
	 */
  EReference getEqualElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.EqualElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.EqualElement#getRight()
	 * @see #getEqualElement()
	 * @generated
	 */
  EReference getEqualElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.LargerElement <em>Larger Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Larger Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.LargerElement
	 * @generated
	 */
  EClass getLargerElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.LargerElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.LargerElement#getLeft()
	 * @see #getLargerElement()
	 * @generated
	 */
  EReference getLargerElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.LargerElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.LargerElement#getRight()
	 * @see #getLargerElement()
	 * @generated
	 */
  EReference getLargerElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.LargerEqualElement <em>Larger Equal Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Larger Equal Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.LargerEqualElement
	 * @generated
	 */
  EClass getLargerEqualElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.LargerEqualElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.LargerEqualElement#getLeft()
	 * @see #getLargerEqualElement()
	 * @generated
	 */
  EReference getLargerEqualElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.LargerEqualElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.LargerEqualElement#getRight()
	 * @see #getLargerEqualElement()
	 * @generated
	 */
  EReference getLargerEqualElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.SmallerElement <em>Smaller Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Smaller Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.SmallerElement
	 * @generated
	 */
  EClass getSmallerElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.SmallerElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.SmallerElement#getLeft()
	 * @see #getSmallerElement()
	 * @generated
	 */
  EReference getSmallerElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.SmallerElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.SmallerElement#getRight()
	 * @see #getSmallerElement()
	 * @generated
	 */
  EReference getSmallerElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.SmallerEqualElement <em>Smaller Equal Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Smaller Equal Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.SmallerEqualElement
	 * @generated
	 */
  EClass getSmallerEqualElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.SmallerEqualElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.SmallerEqualElement#getLeft()
	 * @see #getSmallerEqualElement()
	 * @generated
	 */
  EReference getSmallerEqualElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.SmallerEqualElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.SmallerEqualElement#getRight()
	 * @see #getSmallerEqualElement()
	 * @generated
	 */
  EReference getSmallerEqualElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.PlusElement <em>Plus Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Plus Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.PlusElement
	 * @generated
	 */
  EClass getPlusElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.PlusElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.PlusElement#getLeft()
	 * @see #getPlusElement()
	 * @generated
	 */
  EReference getPlusElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.PlusElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.PlusElement#getRight()
	 * @see #getPlusElement()
	 * @generated
	 */
  EReference getPlusElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.MinusElement <em>Minus Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Minus Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.MinusElement
	 * @generated
	 */
  EClass getMinusElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.MinusElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.MinusElement#getLeft()
	 * @see #getMinusElement()
	 * @generated
	 */
  EReference getMinusElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.MinusElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.MinusElement#getRight()
	 * @see #getMinusElement()
	 * @generated
	 */
  EReference getMinusElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.MultiplicationElement <em>Multiplication Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Multiplication Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.MultiplicationElement
	 * @generated
	 */
  EClass getMultiplicationElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.MultiplicationElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.MultiplicationElement#getLeft()
	 * @see #getMultiplicationElement()
	 * @generated
	 */
  EReference getMultiplicationElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.MultiplicationElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.MultiplicationElement#getRight()
	 * @see #getMultiplicationElement()
	 * @generated
	 */
  EReference getMultiplicationElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.DivisionElement <em>Division Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Division Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.DivisionElement
	 * @generated
	 */
  EClass getDivisionElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.DivisionElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.DivisionElement#getLeft()
	 * @see #getDivisionElement()
	 * @generated
	 */
  EReference getDivisionElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.DivisionElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.DivisionElement#getRight()
	 * @see #getDivisionElement()
	 * @generated
	 */
  EReference getDivisionElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.ModuloElement <em>Modulo Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Modulo Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ModuloElement
	 * @generated
	 */
  EClass getModuloElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.ModuloElement#getLeft <em>Left</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Left</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ModuloElement#getLeft()
	 * @see #getModuloElement()
	 * @generated
	 */
  EReference getModuloElement_Left();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.ModuloElement#getRight <em>Right</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Right</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.ModuloElement#getRight()
	 * @see #getModuloElement()
	 * @generated
	 */
  EReference getModuloElement_Right();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Number_Object <em>Number Object</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Number Object</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Number_Object
	 * @generated
	 */
  EClass getNumber_Object();

  /**
	 * Returns the meta object for the attribute '{@link nii.bigclout.ecaadapter.dsl.Number_Object#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Number_Object#getValue()
	 * @see #getNumber_Object()
	 * @generated
	 */
  EAttribute getNumber_Object_Value();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Boolean_Object <em>Boolean Object</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Boolean Object</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Boolean_Object
	 * @generated
	 */
  EClass getBoolean_Object();

  /**
	 * Returns the meta object for the attribute '{@link nii.bigclout.ecaadapter.dsl.Boolean_Object#isValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the attribute '<em>Value</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Boolean_Object#isValue()
	 * @see #getBoolean_Object()
	 * @generated
	 */
  EAttribute getBoolean_Object_Value();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.Resource_Object <em>Resource Object</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Resource Object</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Resource_Object
	 * @generated
	 */
  EClass getResource_Object();

  /**
	 * Returns the meta object for the reference '{@link nii.bigclout.ecaadapter.dsl.Resource_Object#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the reference '<em>Value</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.Resource_Object#getValue()
	 * @see #getResource_Object()
	 * @generated
	 */
  EReference getResource_Object_Value();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.State_Object <em>State Object</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>State Object</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.State_Object
	 * @generated
	 */
  EClass getState_Object();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.State_Object#getValue <em>Value</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Value</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.State_Object#getValue()
	 * @see #getState_Object()
	 * @generated
	 */
  EReference getState_Object_Value();

  /**
	 * Returns the meta object for class '{@link nii.bigclout.ecaadapter.dsl.NegateElement <em>Negate Element</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for class '<em>Negate Element</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.NegateElement
	 * @generated
	 */
  EClass getNegateElement();

  /**
	 * Returns the meta object for the containment reference '{@link nii.bigclout.ecaadapter.dsl.NegateElement#getExp <em>Exp</em>}'.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the meta object for the containment reference '<em>Exp</em>'.
	 * @see nii.bigclout.ecaadapter.dsl.NegateElement#getExp()
	 * @see #getNegateElement()
	 * @generated
	 */
  EReference getNegateElement_Exp();

  /**
	 * Returns the factory that creates the instances of the model.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @return the factory that creates the instances of the model.
	 * @generated
	 */
  DslFactory getDslFactory();

  /**
	 * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
	 * @generated
	 */
  interface Literals
  {
    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.RunTimeModelImpl <em>Run Time Model</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.RunTimeModelImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getRunTimeModel()
		 * @generated
		 */
    EClass RUN_TIME_MODEL = eINSTANCE.getRunTimeModel();

    /**
		 * The meta object literal for the '<em><b>Env Data</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference RUN_TIME_MODEL__ENV_DATA = eINSTANCE.getRunTimeModel_EnvData();

    /**
		 * The meta object literal for the '<em><b>App Data</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference RUN_TIME_MODEL__APP_DATA = eINSTANCE.getRunTimeModel_AppData();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.StateImpl <em>State</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.StateImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getState()
		 * @generated
		 */
    EClass STATE = eINSTANCE.getState();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.ResourceImpl <em>Resource</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.ResourceImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getResource()
		 * @generated
		 */
    EClass RESOURCE = eINSTANCE.getResource();

    /**
		 * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute RESOURCE__NAME = eINSTANCE.getResource_Name();

    /**
		 * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference RESOURCE__STATES = eINSTANCE.getResource_States();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.AppMetaDataImpl <em>App Meta Data</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.AppMetaDataImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getAppMetaData()
		 * @generated
		 */
    EClass APP_META_DATA = eINSTANCE.getAppMetaData();

    /**
		 * The meta object literal for the '<em><b>App ID</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute APP_META_DATA__APP_ID = eINSTANCE.getAppMetaData_AppID();

    /**
		 * The meta object literal for the '<em><b>Specification</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference APP_META_DATA__SPECIFICATION = eINSTANCE.getAppMetaData_Specification();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.SpecificationImpl <em>Specification</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.SpecificationImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getSpecification()
		 * @generated
		 */
    EClass SPECIFICATION = eINSTANCE.getSpecification();

    /**
		 * The meta object literal for the '<em><b>Spec ID</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SPECIFICATION__SPEC_ID = eINSTANCE.getSpecification_SpecID();

    /**
		 * The meta object literal for the '<em><b>Priority</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute SPECIFICATION__PRIORITY = eINSTANCE.getSpecification_Priority();

    /**
		 * The meta object literal for the '<em><b>Trigger</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SPECIFICATION__TRIGGER = eINSTANCE.getSpecification_Trigger();

    /**
		 * The meta object literal for the '<em><b>Ifdo</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SPECIFICATION__IFDO = eINSTANCE.getSpecification_Ifdo();

    /**
		 * The meta object literal for the '<em><b>Else If Do</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SPECIFICATION__ELSE_IF_DO = eINSTANCE.getSpecification_ElseIfDo();

    /**
		 * The meta object literal for the '<em><b>Else Do</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SPECIFICATION__ELSE_DO = eINSTANCE.getSpecification_ElseDo();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.TriggerImpl <em>Trigger</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.TriggerImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getTrigger()
		 * @generated
		 */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
		 * The meta object literal for the '<em><b>Resource</b></em>' reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference TRIGGER__RESOURCE = eINSTANCE.getTrigger_Resource();

    /**
		 * The meta object literal for the '<em><b>State</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference TRIGGER__STATE = eINSTANCE.getTrigger_State();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.IfDoSpecImpl <em>If Do Spec</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.IfDoSpecImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getIfDoSpec()
		 * @generated
		 */
    EClass IF_DO_SPEC = eINSTANCE.getIfDoSpec();

    /**
		 * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference IF_DO_SPEC__CONDITION = eINSTANCE.getIfDoSpec_Condition();

    /**
		 * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference IF_DO_SPEC__ACTION = eINSTANCE.getIfDoSpec_Action();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.ElseIfDoSpecImpl <em>Else If Do Spec</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.ElseIfDoSpecImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getElseIfDoSpec()
		 * @generated
		 */
    EClass ELSE_IF_DO_SPEC = eINSTANCE.getElseIfDoSpec();

    /**
		 * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ELSE_IF_DO_SPEC__CONDITION = eINSTANCE.getElseIfDoSpec_Condition();

    /**
		 * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ELSE_IF_DO_SPEC__ACTION = eINSTANCE.getElseIfDoSpec_Action();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.ElseDoSpecImpl <em>Else Do Spec</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.ElseDoSpecImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getElseDoSpec()
		 * @generated
		 */
    EClass ELSE_DO_SPEC = eINSTANCE.getElseDoSpec();

    /**
		 * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ELSE_DO_SPEC__ACTION = eINSTANCE.getElseDoSpec_Action();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.EnvironmentMetaDataImpl <em>Environment Meta Data</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.EnvironmentMetaDataImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getEnvironmentMetaData()
		 * @generated
		 */
    EClass ENVIRONMENT_META_DATA = eINSTANCE.getEnvironmentMetaData();

    /**
		 * The meta object literal for the '<em><b>Resources</b></em>' containment reference list feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ENVIRONMENT_META_DATA__RESOURCES = eINSTANCE.getEnvironmentMetaData_Resources();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.ActionImpl <em>Action</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.ActionImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getAction()
		 * @generated
		 */
    EClass ACTION = eINSTANCE.getAction();

    /**
		 * The meta object literal for the '<em><b>Resource</b></em>' reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ACTION__RESOURCE = eINSTANCE.getAction_Resource();

    /**
		 * The meta object literal for the '<em><b>State</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference ACTION__STATE = eINSTANCE.getAction_State();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.ElementImpl <em>Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.ElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getElement()
		 * @generated
		 */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.OrElementImpl <em>Or Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.OrElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getOrElement()
		 * @generated
		 */
    EClass OR_ELEMENT = eINSTANCE.getOrElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference OR_ELEMENT__LEFT = eINSTANCE.getOrElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference OR_ELEMENT__RIGHT = eINSTANCE.getOrElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.AndElementImpl <em>And Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.AndElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getAndElement()
		 * @generated
		 */
    EClass AND_ELEMENT = eINSTANCE.getAndElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference AND_ELEMENT__LEFT = eINSTANCE.getAndElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference AND_ELEMENT__RIGHT = eINSTANCE.getAndElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.DiffElementImpl <em>Diff Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.DiffElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getDiffElement()
		 * @generated
		 */
    EClass DIFF_ELEMENT = eINSTANCE.getDiffElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference DIFF_ELEMENT__LEFT = eINSTANCE.getDiffElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference DIFF_ELEMENT__RIGHT = eINSTANCE.getDiffElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.EqualElementImpl <em>Equal Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.EqualElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getEqualElement()
		 * @generated
		 */
    EClass EQUAL_ELEMENT = eINSTANCE.getEqualElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference EQUAL_ELEMENT__LEFT = eINSTANCE.getEqualElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference EQUAL_ELEMENT__RIGHT = eINSTANCE.getEqualElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.LargerElementImpl <em>Larger Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.LargerElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getLargerElement()
		 * @generated
		 */
    EClass LARGER_ELEMENT = eINSTANCE.getLargerElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference LARGER_ELEMENT__LEFT = eINSTANCE.getLargerElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference LARGER_ELEMENT__RIGHT = eINSTANCE.getLargerElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.LargerEqualElementImpl <em>Larger Equal Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.LargerEqualElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getLargerEqualElement()
		 * @generated
		 */
    EClass LARGER_EQUAL_ELEMENT = eINSTANCE.getLargerEqualElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference LARGER_EQUAL_ELEMENT__LEFT = eINSTANCE.getLargerEqualElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference LARGER_EQUAL_ELEMENT__RIGHT = eINSTANCE.getLargerEqualElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.SmallerElementImpl <em>Smaller Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.SmallerElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getSmallerElement()
		 * @generated
		 */
    EClass SMALLER_ELEMENT = eINSTANCE.getSmallerElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SMALLER_ELEMENT__LEFT = eINSTANCE.getSmallerElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SMALLER_ELEMENT__RIGHT = eINSTANCE.getSmallerElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.SmallerEqualElementImpl <em>Smaller Equal Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.SmallerEqualElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getSmallerEqualElement()
		 * @generated
		 */
    EClass SMALLER_EQUAL_ELEMENT = eINSTANCE.getSmallerEqualElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SMALLER_EQUAL_ELEMENT__LEFT = eINSTANCE.getSmallerEqualElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference SMALLER_EQUAL_ELEMENT__RIGHT = eINSTANCE.getSmallerEqualElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.PlusElementImpl <em>Plus Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.PlusElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getPlusElement()
		 * @generated
		 */
    EClass PLUS_ELEMENT = eINSTANCE.getPlusElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference PLUS_ELEMENT__LEFT = eINSTANCE.getPlusElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference PLUS_ELEMENT__RIGHT = eINSTANCE.getPlusElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.MinusElementImpl <em>Minus Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.MinusElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getMinusElement()
		 * @generated
		 */
    EClass MINUS_ELEMENT = eINSTANCE.getMinusElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MINUS_ELEMENT__LEFT = eINSTANCE.getMinusElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MINUS_ELEMENT__RIGHT = eINSTANCE.getMinusElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.MultiplicationElementImpl <em>Multiplication Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.MultiplicationElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getMultiplicationElement()
		 * @generated
		 */
    EClass MULTIPLICATION_ELEMENT = eINSTANCE.getMultiplicationElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MULTIPLICATION_ELEMENT__LEFT = eINSTANCE.getMultiplicationElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MULTIPLICATION_ELEMENT__RIGHT = eINSTANCE.getMultiplicationElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.DivisionElementImpl <em>Division Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.DivisionElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getDivisionElement()
		 * @generated
		 */
    EClass DIVISION_ELEMENT = eINSTANCE.getDivisionElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference DIVISION_ELEMENT__LEFT = eINSTANCE.getDivisionElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference DIVISION_ELEMENT__RIGHT = eINSTANCE.getDivisionElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.ModuloElementImpl <em>Modulo Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.ModuloElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getModuloElement()
		 * @generated
		 */
    EClass MODULO_ELEMENT = eINSTANCE.getModuloElement();

    /**
		 * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MODULO_ELEMENT__LEFT = eINSTANCE.getModuloElement_Left();

    /**
		 * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference MODULO_ELEMENT__RIGHT = eINSTANCE.getModuloElement_Right();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.Number_ObjectImpl <em>Number Object</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.Number_ObjectImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getNumber_Object()
		 * @generated
		 */
    EClass NUMBER_OBJECT = eINSTANCE.getNumber_Object();

    /**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute NUMBER_OBJECT__VALUE = eINSTANCE.getNumber_Object_Value();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.Boolean_ObjectImpl <em>Boolean Object</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.Boolean_ObjectImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getBoolean_Object()
		 * @generated
		 */
    EClass BOOLEAN_OBJECT = eINSTANCE.getBoolean_Object();

    /**
		 * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EAttribute BOOLEAN_OBJECT__VALUE = eINSTANCE.getBoolean_Object_Value();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.Resource_ObjectImpl <em>Resource Object</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.Resource_ObjectImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getResource_Object()
		 * @generated
		 */
    EClass RESOURCE_OBJECT = eINSTANCE.getResource_Object();

    /**
		 * The meta object literal for the '<em><b>Value</b></em>' reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference RESOURCE_OBJECT__VALUE = eINSTANCE.getResource_Object_Value();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.State_ObjectImpl <em>State Object</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.State_ObjectImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getState_Object()
		 * @generated
		 */
    EClass STATE_OBJECT = eINSTANCE.getState_Object();

    /**
		 * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference STATE_OBJECT__VALUE = eINSTANCE.getState_Object_Value();

    /**
		 * The meta object literal for the '{@link nii.bigclout.ecaadapter.dsl.impl.NegateElementImpl <em>Negate Element</em>}' class.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @see nii.bigclout.ecaadapter.dsl.impl.NegateElementImpl
		 * @see nii.bigclout.ecaadapter.dsl.impl.DslPackageImpl#getNegateElement()
		 * @generated
		 */
    EClass NEGATE_ELEMENT = eINSTANCE.getNegateElement();

    /**
		 * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
		 * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
		 * @generated
		 */
    EReference NEGATE_ELEMENT__EXP = eINSTANCE.getNegateElement_Exp();

  }

} //DslPackage
