/**
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.dsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Negate Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nii.bigclout.ecaadapter.dsl.NegateElement#getExp <em>Exp</em>}</li>
 * </ul>
 *
 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getNegateElement()
 * @model
 * @generated
 */
public interface NegateElement extends Element
{
  /**
	 * Returns the value of the '<em><b>Exp</b></em>' containment reference.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Exp</em>' containment reference.
	 * @see #setExp(Element)
	 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getNegateElement_Exp()
	 * @model containment="true"
	 * @generated
	 */
  Element getExp();

  /**
	 * Sets the value of the '{@link nii.bigclout.ecaadapter.dsl.NegateElement#getExp <em>Exp</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @param value the new value of the '<em>Exp</em>' containment reference.
	 * @see #getExp()
	 * @generated
	 */
  void setExp(Element value);

} // NegateElement
