/**
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Run Time Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nii.bigclout.ecaadapter.dsl.RunTimeModel#getEnvData <em>Env Data</em>}</li>
 *   <li>{@link nii.bigclout.ecaadapter.dsl.RunTimeModel#getAppData <em>App Data</em>}</li>
 * </ul>
 *
 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getRunTimeModel()
 * @model
 * @generated
 */
public interface RunTimeModel extends EObject
{
  /**
	 * Returns the value of the '<em><b>Env Data</b></em>' containment reference list.
	 * The list contents are of type {@link nii.bigclout.ecaadapter.dsl.EnvironmentMetaData}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Env Data</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>Env Data</em>' containment reference list.
	 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getRunTimeModel_EnvData()
	 * @model containment="true"
	 * @generated
	 */
  EList<EnvironmentMetaData> getEnvData();

  /**
	 * Returns the value of the '<em><b>App Data</b></em>' containment reference list.
	 * The list contents are of type {@link nii.bigclout.ecaadapter.dsl.AppMetaData}.
	 * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>App Data</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
	 * @return the value of the '<em>App Data</em>' containment reference list.
	 * @see nii.bigclout.ecaadapter.dsl.DslPackage#getRunTimeModel_AppData()
	 * @model containment="true"
	 * @generated
	 */
  EList<AppMetaData> getAppData();

} // RunTimeModel
