/*
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.serializer;

import com.google.inject.Inject;
import java.util.List;
import nii.bigclout.ecaadapter.services.DslGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class DslSyntacticSequencer extends AbstractSyntacticSequencer {

	protected DslGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Trigger_AreKeyword_1_1_or_IsKeyword_1_0;
	protected AbstractElementAlias match_UnaryElement_LeftParenthesisKeyword_4_0_a;
	protected AbstractElementAlias match_UnaryElement_LeftParenthesisKeyword_4_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (DslGrammarAccess) access;
		match_Trigger_AreKeyword_1_1_or_IsKeyword_1_0 = new AlternativeAlias(false, false, new TokenAlias(false, false, grammarAccess.getTriggerAccess().getAreKeyword_1_1()), new TokenAlias(false, false, grammarAccess.getTriggerAccess().getIsKeyword_1_0()));
		match_UnaryElement_LeftParenthesisKeyword_4_0_a = new TokenAlias(true, true, grammarAccess.getUnaryElementAccess().getLeftParenthesisKeyword_4_0());
		match_UnaryElement_LeftParenthesisKeyword_4_0_p = new TokenAlias(true, false, grammarAccess.getUnaryElementAccess().getLeftParenthesisKeyword_4_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getLBRACERule())
			return getLBRACEToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getRBRACERule())
			return getRBRACEToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * LBRACE: "{";
	 */
	protected String getLBRACEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "{";
	}
	
	/**
	 * RBRACE: "}";
	 */
	protected String getRBRACEToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "}";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Trigger_AreKeyword_1_1_or_IsKeyword_1_0.equals(syntax))
				emit_Trigger_AreKeyword_1_1_or_IsKeyword_1_0(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UnaryElement_LeftParenthesisKeyword_4_0_a.equals(syntax))
				emit_UnaryElement_LeftParenthesisKeyword_4_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_UnaryElement_LeftParenthesisKeyword_4_0_p.equals(syntax))
				emit_UnaryElement_LeftParenthesisKeyword_4_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'is' | 'are'
	 *
	 * This ambiguous syntax occurs at:
	 *     resource=[Resource|ID] (ambiguity) state=State
	 */
	protected void emit_Trigger_AreKeyword_1_1_or_IsKeyword_1_0(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'not' exp=UnaryElement
	 *     (rule start) (ambiguity) value=BOOLEAN
	 *     (rule start) (ambiguity) value=NUMBER
	 *     (rule start) (ambiguity) value=State
	 *     (rule start) (ambiguity) value=[Resource|ID]
	 *     (rule start) (ambiguity) {AndElement.left=}
	 *     (rule start) (ambiguity) {DiffElement.left=}
	 *     (rule start) (ambiguity) {DivisionElement.left=}
	 *     (rule start) (ambiguity) {EqualElement.left=}
	 *     (rule start) (ambiguity) {LargerElement.left=}
	 *     (rule start) (ambiguity) {LargerEqualElement.left=}
	 *     (rule start) (ambiguity) {MinusElement.left=}
	 *     (rule start) (ambiguity) {ModuloElement.left=}
	 *     (rule start) (ambiguity) {MultiplicationElement.left=}
	 *     (rule start) (ambiguity) {OrElement.left=}
	 *     (rule start) (ambiguity) {PlusElement.left=}
	 *     (rule start) (ambiguity) {SmallerElement.left=}
	 *     (rule start) (ambiguity) {SmallerEqualElement.left=}
	 */
	protected void emit_UnaryElement_LeftParenthesisKeyword_4_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {AndElement.left=}
	 *     (rule start) (ambiguity) {DiffElement.left=}
	 *     (rule start) (ambiguity) {DivisionElement.left=}
	 *     (rule start) (ambiguity) {EqualElement.left=}
	 *     (rule start) (ambiguity) {LargerElement.left=}
	 *     (rule start) (ambiguity) {LargerEqualElement.left=}
	 *     (rule start) (ambiguity) {MinusElement.left=}
	 *     (rule start) (ambiguity) {ModuloElement.left=}
	 *     (rule start) (ambiguity) {MultiplicationElement.left=}
	 *     (rule start) (ambiguity) {OrElement.left=}
	 *     (rule start) (ambiguity) {PlusElement.left=}
	 *     (rule start) (ambiguity) {SmallerElement.left=}
	 *     (rule start) (ambiguity) {SmallerEqualElement.left=}
	 */
	protected void emit_UnaryElement_LeftParenthesisKeyword_4_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
