/**
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.dsl.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import nii.bigclout.ecaadapter.dsl.DslFactory;
import nii.bigclout.ecaadapter.dsl.ElseDoSpec;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Else Do Spec</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class ElseDoSpecTest extends TestCase {

	/**
	 * The fixture for this Else Do Spec test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElseDoSpec fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(ElseDoSpecTest.class);
	}

	/**
	 * Constructs a new Else Do Spec test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ElseDoSpecTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this Else Do Spec test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(ElseDoSpec fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this Else Do Spec test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElseDoSpec getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DslFactory.eINSTANCE.createElseDoSpec());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //ElseDoSpecTest
