/**
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.dsl.tests;

import junit.textui.TestRunner;

import nii.bigclout.ecaadapter.dsl.DslFactory;
import nii.bigclout.ecaadapter.dsl.EqualElement;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Equal Element</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class EqualElementTest extends ElementTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(EqualElementTest.class);
	}

	/**
	 * Constructs a new Equal Element test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EqualElementTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Equal Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EqualElement getFixture() {
		return (EqualElement)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DslFactory.eINSTANCE.createEqualElement());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //EqualElementTest
