/**
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.dsl.tests;

import junit.textui.TestRunner;

import nii.bigclout.ecaadapter.dsl.DslFactory;
import nii.bigclout.ecaadapter.dsl.MultiplicationElement;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Multiplication Element</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class MultiplicationElementTest extends ElementTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(MultiplicationElementTest.class);
	}

	/**
	 * Constructs a new Multiplication Element test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public MultiplicationElementTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Multiplication Element test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected MultiplicationElement getFixture() {
		return (MultiplicationElement)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DslFactory.eINSTANCE.createMultiplicationElement());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //MultiplicationElementTest
