/**
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.dsl.tests;

import junit.textui.TestRunner;

import nii.bigclout.ecaadapter.dsl.DslFactory;
import nii.bigclout.ecaadapter.dsl.Resource_Object;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>Resource Object</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class Resource_ObjectTest extends ElementTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(Resource_ObjectTest.class);
	}

	/**
	 * Constructs a new Resource Object test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Resource_ObjectTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this Resource Object test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected Resource_Object getFixture() {
		return (Resource_Object)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(DslFactory.eINSTANCE.createResource_Object());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //Resource_ObjectTest
