/**
 * generated by Xtext 2.13.0
 */
package nii.bigclout.ecaadapter.scoping;

import nii.bigclout.ecaadapter.scoping.AbstractDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class DslScopeProvider extends AbstractDslScopeProvider {
}
