/*
 * generated by Xtext 2.13.0.RC1
 */
package nii.bigclout.ecaadapter.ui.tests;

import com.google.inject.Injector;
import nii.bigclout.ecaadapter.dsl.ui.internal.DslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("nii.bigclout.ecaadapter.Dsl");
	}

}
