/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.sensinact.studio.language.sensinact.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.eclipse.sensinact.studio.language.sensinact.DSL_On;
import org.eclipse.sensinact.studio.language.sensinact.SensinactFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>DSL On</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DSL_OnTest extends TestCase {

	/**
	 * The fixture for this DSL On test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_On fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DSL_OnTest.class);
	}

	/**
	 * Constructs a new DSL On test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DSL_OnTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this DSL On test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(DSL_On fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this DSL On test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_On getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SensinactFactory.eINSTANCE.createDSL_On());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DSL_OnTest
