/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.sensinact.studio.language.sensinact.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.eclipse.sensinact.studio.language.sensinact.DSL_SENSINACT;
import org.eclipse.sensinact.studio.language.sensinact.SensinactFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>DSL SENSINACT</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DSL_SENSINACTTest extends TestCase {

	/**
	 * The fixture for this DSL SENSINACT test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_SENSINACT fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DSL_SENSINACTTest.class);
	}

	/**
	 * Constructs a new DSL SENSINACT test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DSL_SENSINACTTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this DSL SENSINACT test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(DSL_SENSINACT fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this DSL SENSINACT test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_SENSINACT getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SensinactFactory.eINSTANCE.createDSL_SENSINACT());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DSL_SENSINACTTest
