/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.sensinact.studio.language.sensinact.tests;

import junit.textui.TestRunner;

import org.eclipse.sensinact.studio.language.sensinact.DSL_Expression_Equal;
import org.eclipse.sensinact.studio.language.sensinact.SensinactFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>DSL Expression Equal</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DSL_Expression_EqualTest extends DSL_ExpressionTest {

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DSL_Expression_EqualTest.class);
	}

	/**
	 * Constructs a new DSL Expression Equal test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DSL_Expression_EqualTest(String name) {
		super(name);
	}

	/**
	 * Returns the fixture for this DSL Expression Equal test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected DSL_Expression_Equal getFixture() {
		return (DSL_Expression_Equal)fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SensinactFactory.eINSTANCE.createDSL_Expression_Equal());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DSL_Expression_EqualTest
