/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.sensinact.studio.language.sensinact.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.eclipse.sensinact.studio.language.sensinact.DSL_IfDo;
import org.eclipse.sensinact.studio.language.sensinact.SensinactFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>DSL If Do</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DSL_IfDoTest extends TestCase {

	/**
	 * The fixture for this DSL If Do test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_IfDo fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DSL_IfDoTest.class);
	}

	/**
	 * Constructs a new DSL If Do test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DSL_IfDoTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this DSL If Do test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(DSL_IfDo fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this DSL If Do test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_IfDo getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SensinactFactory.eINSTANCE.createDSL_IfDo());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DSL_IfDoTest
