/**
 * generated by Xtext 2.12.0
 */
package org.eclipse.sensinact.studio.language.sensinact.tests;

import junit.framework.TestCase;

import junit.textui.TestRunner;

import org.eclipse.sensinact.studio.language.sensinact.DSL_ECA_STATEMENT;
import org.eclipse.sensinact.studio.language.sensinact.SensinactFactory;

/**
 * <!-- begin-user-doc -->
 * A test case for the model object '<em><b>DSL ECA STATEMENT</b></em>'.
 * <!-- end-user-doc -->
 * @generated
 */
public class DSL_ECA_STATEMENTTest extends TestCase {

	/**
	 * The fixture for this DSL ECA STATEMENT test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ECA_STATEMENT fixture = null;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static void main(String[] args) {
		TestRunner.run(DSL_ECA_STATEMENTTest.class);
	}

	/**
	 * Constructs a new DSL ECA STATEMENT test case with the given name.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public DSL_ECA_STATEMENTTest(String name) {
		super(name);
	}

	/**
	 * Sets the fixture for this DSL ECA STATEMENT test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected void setFixture(DSL_ECA_STATEMENT fixture) {
		this.fixture = fixture;
	}

	/**
	 * Returns the fixture for this DSL ECA STATEMENT test case.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DSL_ECA_STATEMENT getFixture() {
		return fixture;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#setUp()
	 * @generated
	 */
	@Override
	protected void setUp() throws Exception {
		setFixture(SensinactFactory.eINSTANCE.createDSL_ECA_STATEMENT());
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see junit.framework.TestCase#tearDown()
	 * @generated
	 */
	@Override
	protected void tearDown() throws Exception {
		setFixture(null);
	}

} //DSL_ECA_STATEMENTTest
